import { readFileSync } from "fs";
import { resolve } from "path";
try {
  const e = readFileSync(resolve(process.cwd(), ".env.local"), "utf8");
  for (const l of e.split("\n")) { const m = l.match(/^([^#=]+)=(.*)/); if (m) process.env[m[1].trim()] = m[2].trim(); }
} catch {}
import { createClient } from "@supabase/supabase-js";
const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });

const S3 = "https://s3.amazonaws.com/a.teamworksales.com";
const HL = `${S3}/HIGHLEAD`;
const YM = `${S3}/YAMATO-PDF/NEW%20YAMATO`;
const BR = `${S3}/BROTHER-PDF`;
const KA = `${S3}/KANSAI-PDF/INSTRUCTION%20IN%20ENG`;
const PG = `${S3}/PEGASUS-PDF`;
const PI = `${S3}/PEGASUS-PDF/PEG%20INSTRUCTIONS`;
const CN = `${S3}/CONSEW%20PDF/CONSEW%20NEW`;
const CO = `${S3}/CONSEW%20PDF`;
const SI = `${S3}/SINGER%20INSTRUCTIONS`;

type M = { slug: string; brand_slug: string; model_name: string; category: string;
  description: string; max_speed_spm?: number; needle_system?: string;
  needle_size_range?: string; discontinued?: boolean; manual_url: string; manual_source: string };

const MACHINES: M[] = [

// ══ HIGHLEAD — GC series flatbed lockstitch ═══════════════════════════════════

{ slug:"highlead-gc128", brand_slug:"highlead", model_name:"GC128", category:"lockstitch",
  description:"Highlead GC128 high-speed flatbed lockstitch for light to medium apparel fabrics. A reliable entry-level industrial lockstitch from Highlead for shirt, blouse, and casual wear factories.",
  max_speed_spm:5500, needle_system:"DB×1", needle_size_range:"9–16",
  manual_url:`${HL}/HIGHLEAD%20GC128%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc0068-1", brand_slug:"highlead", model_name:"GC0068-1", category:"lockstitch",
  description:"Highlead GC0068-1 lockstitch for the lightest fabrics — voile, chiffon, and organza. Specifically tuned for sheer and delicate fabrics requiring minimal presser foot pressure.",
  max_speed_spm:5000, needle_system:"DB×1", needle_size_range:"7–11",
  manual_url:`${HL}/HIGHLEAD%20GC0068-1%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc188-m", brand_slug:"highlead", model_name:"GC188-M", category:"lockstitch",
  description:"Highlead GC188-M industrial lockstitch for medium-weight fabrics. A versatile mid-range lockstitch handling shirt, trouser, and casual wear production in general-purpose garment factories.",
  max_speed_spm:5500, needle_system:"DB×1", needle_size_range:"9–18",
  manual_url:`${HL}/HIGHLEAD%20GC188-M%20-H%20-B%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc188-mc", brand_slug:"highlead", model_name:"GC188-MC", category:"lockstitch",
  description:"Highlead GC188-MC lockstitch with automatic thread cutter. Adds automatic thread trimming to the GC188 platform for faster cycle times and reduced operator fatigue.",
  max_speed_spm:5500, needle_system:"DB×1", needle_size_range:"9–18",
  manual_url:`${HL}/HIGHLEAD%20GC188-MC%20GC188-MC-D%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc1088", brand_slug:"highlead", model_name:"GC1088", category:"lockstitch",
  description:"Highlead GC1088 heavy-duty industrial lockstitch for denim and workwear. A more powerful lockstitch than the GC188 series for production sewing of heavy denim, canvas, and thick fabrics.",
  max_speed_spm:5000, needle_system:"DB×1", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC1088%20instruction%20manual.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc1870-m", brand_slug:"highlead", model_name:"GC1870-M", category:"lockstitch",
  description:"Highlead GC1870-M 2-needle lockstitch for parallel topstitching. Produces two rows of lockstitch simultaneously for collar attachment, waistband topstitching, and decorative seaming.",
  max_speed_spm:4500, needle_system:"DP×17", needle_size_range:"11–18",
  manual_url:`${HL}/HIGHLEAD%20GC1870-M%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc1988-md", brand_slug:"highlead", model_name:"GC1988-MD", category:"lockstitch",
  description:"Highlead GC1988-MD heavy 2-needle lockstitch for denim topstitching. Delivers the bold twin rows of topstitching on jeans pockets and waistbands with heavy thread.",
  max_speed_spm:4000, needle_system:"DP×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC1988-MD%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc1998", brand_slug:"highlead", model_name:"GC1998", category:"walking-foot",
  description:"Highlead GC1998 compound-feed walking-foot lockstitch for leather and vinyl. A medium-duty walking-foot machine for leatherette, genuine leather, and vinyl goods production.",
  max_speed_spm:3000, needle_system:"135×17", needle_size_range:"14–18",
  manual_url:`${HL}/HIGHLEAD%20GC1998%20Parts%20book%20and%20Instruction%20manual.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc2008-m", brand_slug:"highlead", model_name:"GC2008-M", category:"lockstitch",
  description:"Highlead GC2008-M heavy lockstitch for thick industrial fabrics. A large-hook machine handling the heavy thread and thick fabric used in workwear and industrial garment production.",
  max_speed_spm:4500, needle_system:"DB×1", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC2008-M%20%20GC2008-MD%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc2268", brand_slug:"highlead", model_name:"GC2268", category:"lockstitch",
  description:"Highlead GC2268 2-needle lockstitch for wide-gauge topstitching on industrial garments. Handles wider needle spacing than the GC1870-M for different topstitching requirements.",
  max_speed_spm:4000, needle_system:"DP×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC2268%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc22618", brand_slug:"highlead", model_name:"GC22618", category:"lockstitch",
  description:"Highlead GC22618 2-needle cylinder-arm lockstitch for cylindrical workpieces. Combines 2-needle parallel stitching with a cylinder arm for bag handles and boot shafts.",
  max_speed_spm:4000, needle_system:"DP×17", needle_size_range:"11–18",
  manual_url:`${HL}/HIGHLEAD%20GC22618%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc22682bl", brand_slug:"highlead", model_name:"GC22682BL", category:"lockstitch",
  description:"Highlead GC22682BL long-arm 2-needle lockstitch for wide leather panels and large bags. The long-arm (BL = big long arm) provides clearance for sewing the sides of large bags.",
  max_speed_spm:3500, needle_system:"DP×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC22682BL%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc28", brand_slug:"highlead", model_name:"GC28", category:"lockstitch",
  description:"Highlead GC28 medium lockstitch for general apparel and accessories. A widely-used mid-series Highlead lockstitch for shirt, trouser, and casual wear production.",
  max_speed_spm:5000, needle_system:"DB×1", needle_size_range:"9–18",
  manual_url:`${HL}/HIGHLEAD%20GC28%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc518", brand_slug:"highlead", model_name:"GC518", category:"lockstitch",
  description:"Highlead GC518 heavy lockstitch for denim and heavyweight fabrics. A production workhorse for denim jeans, workwear, and canvas goods requiring penetration power and heavy thread.",
  max_speed_spm:4500, needle_system:"DB×1", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC518%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc518-mc", brand_slug:"highlead", model_name:"GC518-MC", category:"lockstitch",
  description:"Highlead GC518-MC heavy lockstitch with automatic thread cutter for denim production. Adds automatic trimming to the GC518 for faster production cycles in denim jeans factories.",
  max_speed_spm:4500, needle_system:"DB×1", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC518-MC%20GC518-MC-D%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },

// ══ HIGHLEAD — GC20xxx post-bed cylinder arm ══════════════════════════════════

{ slug:"highlead-gc20518", brand_slug:"highlead", model_name:"GC20518", category:"post-bed",
  description:"Highlead GC20518 post-bed cylinder-arm lockstitch for shoes and cylindrical leather goods. A modern Highlead cylinder-arm machine for light to medium footwear and leather accessories.",
  max_speed_spm:3500, needle_system:"135×17", needle_size_range:"11–18",
  manual_url:`${HL}/HIGHLEAD%20GC20518%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc20528", brand_slug:"highlead", model_name:"GC20528", category:"post-bed",
  description:"Highlead GC20528 post-bed cylinder-arm lockstitch series for leather goods and shoe production. An updated cylinder-arm platform with improved feed for consistent stitching around cylindrical pieces.",
  max_speed_spm:3500, needle_system:"135×17", needle_size_range:"11–18",
  manual_url:`${HL}/HIGHLEAD%20GC20528%20Series%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc20618", brand_slug:"highlead", model_name:"GC20618", category:"post-bed",
  description:"Highlead GC20618 medium post-bed cylinder-arm lockstitch for bag and leather goods manufacturing. Handles medium-weight leather in bag body, strap, and accessory production.",
  max_speed_spm:3000, needle_system:"135×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC20618%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc20638", brand_slug:"highlead", model_name:"GC20638", category:"post-bed",
  description:"Highlead GC20638 heavy post-bed cylinder-arm for boots and saddle production. Handles the thick leather in western boot vamps, cowboy boot tops, and heavy saddle pieces.",
  max_speed_spm:2500, needle_system:"135×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC20638%20GC20638-D%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc20638-25", brand_slug:"highlead", model_name:"GC20638-25", category:"post-bed",
  description:"Highlead GC20638-25 heavy post-bed cylinder-arm with 25mm stitch length for thick saddle leather. The extended stitch length capability handles heavy saddle-tree stitching with thick waxed thread.",
  max_speed_spm:2000, needle_system:"135×17", needle_size_range:"18–25",
  manual_url:`${HL}/HIGHLEAD%20GC20638-25%2C%20GC20638-25D%20Parts%20catalog%20and%20Instruction%20Manual.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc20688-1-d", brand_slug:"highlead", model_name:"GC20688-1-D", category:"post-bed",
  description:"Highlead GC20688-1-D direct-drive post-bed cylinder-arm for medium-heavy leather goods. The D (direct drive) eliminates the clutch motor for quieter, more energy-efficient production.",
  max_speed_spm:3000, needle_system:"135×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC20688-1-D%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc20688-12bdl", brand_slug:"highlead", model_name:"GC20688-12BDL", category:"post-bed",
  description:"Highlead GC20688-12BDL large-arm direct-drive post-bed cylinder for boot-shaft stitching. The BDL (big drum long) configuration provides maximum post depth for the tallest boot shafts.",
  max_speed_spm:2500, needle_system:"135×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC20688-12BDL%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc20698", brand_slug:"highlead", model_name:"GC20698", category:"post-bed",
  description:"Highlead GC20698 post-bed cylinder-arm with roller presser for synthetic leather and vinyl. The roller presser prevents the non-stick synthetic material from dragging on the presser foot.",
  max_speed_spm:3000, needle_system:"135×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC20698%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc20818-md", brand_slug:"highlead", model_name:"GC20818-MD", category:"post-bed",
  description:"Highlead GC20818-MD 2-needle direct-drive post-bed cylinder-arm for dual-row boot stitching. Produces two parallel rows simultaneously for the decorative and structural stitching on cowboy boots.",
  max_speed_spm:2500, needle_system:"DP×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC20818-MD%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },

// ══ HIGHLEAD — GC24xxx extra-heavy cylinder arm ═══════════════════════════════

{ slug:"highlead-gc24018", brand_slug:"highlead", model_name:"GC24018", category:"post-bed",
  description:"Highlead GC24018 extra-heavy post-bed cylinder-arm for thick leather goods and welt shoe stitching. A step up from the GC20618 for the heaviest boot welts and thick bag stitching.",
  max_speed_spm:2000, needle_system:"135×17", needle_size_range:"18–25",
  manual_url:`${HL}/HIGHLEAD%20GC24018%20GC24018-1%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc24518", brand_slug:"highlead", model_name:"GC24518", category:"post-bed",
  description:"Highlead GC24518 extra-heavy post-bed cylinder-arm for welt shoe construction and saddlery. Handles the heavy multi-layer leather and waxed thread used in Goodyear welt shoe manufacturing.",
  max_speed_spm:1800, needle_system:"135×17", needle_size_range:"18–25",
  manual_url:`${HL}/HIGHLEAD%20GC24518-1%20GC24518-2%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc24608", brand_slug:"highlead", model_name:"GC24608", category:"post-bed",
  description:"Highlead GC24608 large extra-heavy post-bed cylinder-arm for saddle and harness making. A specialist machine for large-diameter cylindrical leather pieces used in Western saddlery.",
  max_speed_spm:1500, needle_system:"135×17", needle_size_range:"21–28",
  manual_url:`${HL}/HIGHLEAD%20GC24608-2%20GC24608-1L%201R%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc24618", brand_slug:"highlead", model_name:"GC24618", category:"post-bed",
  description:"Highlead GC24618 super-heavy post-bed cylinder-arm for harness and saddlery. One of Highlead's most powerful cylinder-arm machines for the thickest harness leather.",
  max_speed_spm:1500, needle_system:"135×17", needle_size_range:"21–28",
  manual_url:`${HL}/HIGHLEAD%20GC24618%20GC24618-1%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc24628", brand_slug:"highlead", model_name:"GC24628", category:"post-bed",
  description:"Highlead GC24628 extra-heavy cylinder-arm for the heaviest harness and saddle-tree leather. Used in professional saddle making for stitching through the multiple layers at seat seams.",
  max_speed_spm:1200, needle_system:"135×17", needle_size_range:"23–30",
  manual_url:`${HL}/HIGHLEAD%20GC24628%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc24688", brand_slug:"highlead", model_name:"GC24688", category:"post-bed",
  description:"Highlead GC24688 cylinder-arm with roller presser for thick synthetic leather goods. Handles non-stick synthetic leathers and vinyls that standard presser feet cannot grip properly.",
  max_speed_spm:1500, needle_system:"135×17", needle_size_range:"18–25",
  manual_url:`${HL}/HIGHLEAD%20GC24688%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc24698-1l", brand_slug:"highlead", model_name:"GC24698-1L/1R", category:"post-bed",
  description:"Highlead GC24698-1L/1R left and right-hand cylinder-arm for paired production lines. Left and right configurations for factories using two-sided assembly layouts.",
  max_speed_spm:1500, needle_system:"135×17", needle_size_range:"21–28",
  manual_url:`${HL}/HIGHLEAD%20GC24698-1L%20GC24698-1R%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc24698-25", brand_slug:"highlead", model_name:"GC24698-25", category:"post-bed",
  description:"Highlead GC24698-25 extra-heavy cylinder-arm with 25mm stitch for harness and military webbing. The long stitch capability handles the structural stitching on heavy harness and webbing.",
  max_speed_spm:1200, needle_system:"135×17", needle_size_range:"23–30",
  manual_url:`${HL}/HIGHLEAD%20GC24698-25L%20-25R%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc24698-2b", brand_slug:"highlead", model_name:"GC24698-2B", category:"post-bed",
  description:"Highlead GC24698-2B big-drum cylinder-arm for large-diameter leather goods. The 2B configuration has the largest drum diameter in the GC24698 series for the widest cylindrical pieces.",
  max_speed_spm:1200, needle_system:"135×17", needle_size_range:"23–30",
  manual_url:`${HL}/HIGHLEAD%20GC24698-2B%20-BL%20-BR%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc24698-56", brand_slug:"highlead", model_name:"GC24698-56", category:"post-bed",
  description:"Highlead GC24698-56 heavy cylinder-arm with 56mm stitch for the thickest industrial materials. Extremely long stitch capability for military harness and heavy industrial leather goods.",
  max_speed_spm:1000, needle_system:"794 H", needle_size_range:"25–35",
  manual_url:`${HL}/HIGHLEAD%20GC24698-56%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },

// ══ HIGHLEAD — GA, GG, GK, GL, GM series ═════════════════════════════════════

{ slug:"highlead-ga0688-1", brand_slug:"highlead", model_name:"GA0688-1", category:"walking-foot",
  description:"Highlead GA0688-1 compound-feed walking-foot lockstitch for light leather and vinyl. An entry-level walking-foot machine from Highlead's GA series for leatherette and light leather goods.",
  max_speed_spm:3000, needle_system:"135×17", needle_size_range:"14–18",
  manual_url:`${HL}/HIGHLEAD%20GA0688-1%20instructions%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-ga1398-1", brand_slug:"highlead", model_name:"GA1398-1", category:"walking-foot",
  description:"Highlead GA1398-1 compound-feed walking-foot for medium leather goods and upholstery. A mid-range walking-foot machine for furniture upholstery, leather bags, and automotive applications.",
  max_speed_spm:2800, needle_system:"135×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GA1398-1%20instructions%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-ga2388-1", brand_slug:"highlead", model_name:"GA2388-1", category:"walking-foot",
  description:"Highlead GA2388-1 heavy compound-feed walking-foot for thick leather upholstery and marine applications. Handles the thick material in marine boat seating, truck cab interiors, and heavy furniture.",
  max_speed_spm:2500, needle_system:"135×17", needle_size_range:"16–23",
  manual_url:`${HL}/HIGHLEAD%20GA2388-1%20Instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-ga2688-1", brand_slug:"highlead", model_name:"GA2688-1", category:"walking-foot",
  description:"Highlead GA2688-1 extra-heavy compound-feed walking-foot for the thickest leather panels. Used in the production of heavy saddles, marine upholstery, and thick leather equipment.",
  max_speed_spm:2000, needle_system:"135×17", needle_size_range:"18–25",
  manual_url:`${HL}/HIGHLEAD%20GA2688-1%20instructions%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-ga2698-1", brand_slug:"highlead", model_name:"GA2698-1", category:"walking-foot",
  description:"Highlead GA2698-1 super-heavy compound-feed walking-foot for the heaviest industrial leather and canvas. The most powerful machine in the Highlead GA walking-foot series for extreme applications.",
  max_speed_spm:1800, needle_system:"794 H", needle_size_range:"21–28",
  manual_url:`${HL}/HIGHLEAD%20GA2698-1%20Instructions%20Manual%20and%20Parts%20Catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gg0068-1", brand_slug:"highlead", model_name:"GG0068-1", category:"lockstitch",
  description:"Highlead GG0068-1 2-needle lockstitch for fine parallel topstitching. Produces very close-spaced twin rows for delicate topstitching on shirt collars and dress seams.",
  max_speed_spm:4500, needle_system:"DP×17", needle_size_range:"9–14",
  manual_url:`${HL}/HIGHLEAD%20GG0068-1%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gg28-l", brand_slug:"highlead", model_name:"GG28-L", category:"lockstitch",
  description:"Highlead GG28-L long-arm 2-needle lockstitch for wide fabric panels. The L (long arm) provides extra clearance for sewing wide fabric pieces requiring 2-needle parallel stitching.",
  max_speed_spm:4000, needle_system:"DP×17", needle_size_range:"11–18",
  manual_url:`${HL}/HIGHLEAD%20GG28-L%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gg80018", brand_slug:"highlead", model_name:"GG80018", category:"lockstitch",
  description:"Highlead GG80018 heavy 2-needle lockstitch for denim and heavy fabric topstitching. A powerful 2-needle machine for the heavy double-needle topstitching on jeans and workwear.",
  max_speed_spm:3500, needle_system:"DP×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GG80018%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gk0088", brand_slug:"highlead", model_name:"GK0088", category:"post-bed",
  description:"Highlead GK0088 post-bed cylinder-arm lockstitch for light shoe and leather goods production. A light-duty cylinder-arm machine for soft leather accessories and light footwear assembly.",
  max_speed_spm:3500, needle_system:"135×17", needle_size_range:"11–16",
  manual_url:`${HL}/HIGHLEAD%20GK0088%20Parts%20and%20Instruction%20Manual.pdf`, manual_source:"retailer" },
{ slug:"highlead-gk3088-2", brand_slug:"highlead", model_name:"GK3088-2", category:"post-bed",
  description:"Highlead GK3088-2 medium post-bed cylinder-arm for bags and boot production. Handles medium leather in the GK cylinder-arm series for structured bag bodies and ankle boots.",
  max_speed_spm:3000, needle_system:"135×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GK3088-2%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gk31058", brand_slug:"highlead", model_name:"GK31058", category:"post-bed",
  description:"Highlead GK31058 series post-bed cylinder-arm for medium-heavy leather goods. A stepped-up cylinder-arm machine in the GK series for medium-heavy leather bag and boot production.",
  max_speed_spm:2800, needle_system:"135×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GK31058%20series%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gk500", brand_slug:"highlead", model_name:"GK500", category:"post-bed",
  description:"Highlead GK500 heavy post-bed cylinder-arm for boot shafts and thick bags. A powerful cylinder-arm from Highlead's GK series for heavy leather in premium boots and structured bags.",
  max_speed_spm:2500, needle_system:"135×17", needle_size_range:"18–25",
  manual_url:`${HL}/HIGHLEAD%20GK500%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gk600", brand_slug:"highlead", model_name:"GK600", category:"post-bed",
  description:"Highlead GK600 extra-heavy post-bed cylinder-arm for the thickest leather goods and saddlery. The heaviest machine in the GK series for premium heavy-leather product manufacturing.",
  max_speed_spm:2000, needle_system:"135×17", needle_size_range:"21–28",
  manual_url:`${HL}/HIGHLEAD%20GK600%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gl13118-1", brand_slug:"highlead", model_name:"GL13118-1", category:"lockstitch",
  description:"Highlead GL13118-1 long-arm flatbed lockstitch for sewing long seams on large leather panels. The extended machine arm allows sewing far from the edge on large furniture and automotive panels.",
  max_speed_spm:4000, needle_system:"DB×1", needle_size_range:"11–18",
  manual_url:`${HL}/HIGHLEAD%20GL13118-1%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gl13128-1", brand_slug:"highlead", model_name:"GL13128-1", category:"lockstitch",
  description:"Highlead GL13128-1 long-arm 2-needle lockstitch for wide-panel double-row topstitching. Combines the GL long arm with 2-needle capability for decorative parallel stitching on large leather panels.",
  max_speed_spm:3500, needle_system:"DP×17", needle_size_range:"11–18",
  manual_url:`${HL}/HIGHLEAD%20GL13128-1%20instruction%20manual.pdf`, manual_source:"retailer" },
{ slug:"highlead-gl13138-1", brand_slug:"highlead", model_name:"GL13138-1", category:"lockstitch",
  description:"Highlead GL13138-1 extra-long-arm lockstitch for the largest leather panels and upholstery. Maximum arm length for sewing the center of wide automotive panels and large furniture pieces.",
  max_speed_spm:3500, needle_system:"DB×1", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GL13138-1%20Instructions%20%26%20Parts%20Catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gl22018", brand_slug:"highlead", model_name:"GL22018", category:"lockstitch",
  description:"Highlead GL22018 long-arm flatbed lockstitch for automotive upholstery and large leather goods. Produces consistent stitching far from the fabric edge on wide automotive door panels.",
  max_speed_spm:4000, needle_system:"DB×1", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GL22018%20Instructions%20%26%20Parts%20Catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gm288-3", brand_slug:"highlead", model_name:"GM288-3/4/5", category:"lockstitch",
  description:"Highlead GM288-3/4/5 multi-needle lockstitch for multiple parallel rows of decorative stitching. Applies 3, 4, or 5 rows of lockstitch simultaneously for complex decorative applications on leather goods.",
  max_speed_spm:3500, needle_system:"DP×17", needle_size_range:"11–18",
  manual_url:`${HL}/HIGHLEAD%20GM288-3%20%20%20GM288-4%20%20%20GM288-5%20Parts%20catalog%20and%20Instructions%20manual.pdf`, manual_source:"retailer" },
{ slug:"highlead-gm700", brand_slug:"highlead", model_name:"GM700", category:"lockstitch",
  description:"Highlead GM700 multi-needle lockstitch for wide decorative topstitching bands on waistbands and bags. Produces multiple rows of uniform lockstitch for the decorative panels in leather goods.",
  max_speed_spm:3000, needle_system:"DP×17", needle_size_range:"11–21",
  manual_url:`${HL}/HIGHLEAD%20GM700%20Instructions%20%26%20Parts%20Catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc6-28-1", brand_slug:"highlead", model_name:"GC6-28-1", category:"lockstitch",
  description:"Highlead GC6-28-1 heavy-duty lockstitch for thick industrial fabrics. A specialized Highlead heavy lockstitch with extra-large hook for handling thick thread and multiple fabric layers.",
  max_speed_spm:4000, needle_system:"DB×1", needle_size_range:"16–23",
  manual_url:`${HL}/HIGHLEAD%20GC6-28-1%20GC6-28-1H%20GC6-28-1B%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc0318-1", brand_slug:"highlead", model_name:"GC0318-1/2/8", category:"post-bed",
  description:"Highlead GC0318 light post-bed cylinder-arm for soft leather accessories and light footwear. An entry-level cylinder-arm machine for soft leather goods like wallets, belts, and light sandals.",
  max_speed_spm:4000, needle_system:"135×17", needle_size_range:"9–14",
  manual_url:`${HL}/HIGHLEAD%20GC0318-1%20%20GC0318-2%20%20GC0318-8%20%20GC0618%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc0360-1", brand_slug:"highlead", model_name:"GC0360-1", category:"post-bed",
  description:"Highlead GC0360-1 light post-bed cylinder-arm for fine leather goods and watch straps. A specialist cylinder-arm for the narrow-diameter drum needed to stitch watch straps and narrow leather items.",
  max_speed_spm:3500, needle_system:"135×17", needle_size_range:"9–14",
  manual_url:`${HL}/HIGHLEAD%20GC0360-1%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc0388", brand_slug:"highlead", model_name:"GC0388/GC388-D", category:"post-bed",
  description:"Highlead GC0388 post-bed cylinder-arm for light leather goods and shoe components. A light-duty cylinder-arm from Highlead for soft leather shoe components and accessories.",
  max_speed_spm:3500, needle_system:"135×17", needle_size_range:"9–16",
  manual_url:`${HL}/HIGHLEAD%20GC388-D%20GC0388%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc318-1a", brand_slug:"highlead", model_name:"GC318-1A", category:"post-bed",
  description:"Highlead GC318-1A medium post-bed cylinder-arm for shoe uppers and leather accessories. A well-rounded cylinder-arm machine for standard footwear upper assembly and leather goods.",
  max_speed_spm:3000, needle_system:"135×17", needle_size_range:"11–18",
  manual_url:`${HL}/HIGHLEAD%20GC318-1A%20GC0318-1H%20GC0318-1B%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc0918-1-d", brand_slug:"highlead", model_name:"GC0918-1-D", category:"post-bed",
  description:"Highlead GC0918-1-D direct-drive post-bed cylinder-arm for medium leather goods. A modern direct-drive cylinder-arm machine replacing clutch motors for quieter, more efficient production.",
  max_speed_spm:3500, needle_system:"135×17", needle_size_range:"14–18",
  manual_url:`${HL}/HIGHLEAD%20GC918-1-D%20GC0918-1%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc2698-2", brand_slug:"highlead", model_name:"GC2698-2", category:"post-bed",
  description:"Highlead GC2698-2 medium-heavy cylinder-arm lockstitch for bags and boot production. A versatile cylinder-arm machine for medium-heavy leather goods in bag and premium footwear manufacturing.",
  max_speed_spm:2500, needle_system:"135×17", needle_size_range:"14–21",
  manual_url:`${HL}/HIGHLEAD%20GC2698-2%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-gc398-1", brand_slug:"highlead", model_name:"GC398-1/GC0398-1-D", category:"post-bed",
  description:"Highlead GC398-1 post-bed cylinder-arm lockstitch for medium shoe and bag production. A direct-drive version offers quieter operation for medium-weight leather goods factories.",
  max_speed_spm:3000, needle_system:"135×17", needle_size_range:"11–18",
  manual_url:`${HL}/HIGHLEAD%20GC398-1%20GC0398-1-D%20instruction%20manual%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-hlk-1510", brand_slug:"highlead", model_name:"HLK-1510", category:"walking-foot",
  description:"Highlead HLK-1510 heavy walking-foot lockstitch for upholstery and thick canvas. A powerful walking-foot machine in Highlead's HLK series for industrial upholstery and technical textile applications.",
  max_speed_spm:2000, needle_system:"794 H", needle_size_range:"18–25",
  manual_url:`${HL}/HIGHLEAD%20HLK-1510%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-hly-18b-m", brand_slug:"highlead", model_name:"HLY-18B/M", category:"lockstitch",
  description:"Highlead HLY-18B/M medium lockstitch for medium-weight apparel and accessories. A versatile mid-series Highlead lockstitch for production sewing of multiple garment types.",
  max_speed_spm:5000, needle_system:"DB×1", needle_size_range:"9–18",
  manual_url:`${HL}/HIGHLEAD%20HLY-18B_M%20Instructions%20%26%20Parts%20Catalog.pdf`, manual_source:"retailer" },
{ slug:"highlead-czm200", brand_slug:"highlead", model_name:"CZM200", category:"lockstitch",
  description:"Highlead CZM200 zigzag lockstitch for elastic attachment, appliqué, and decorative sewing. A high-speed zigzag machine for elastic attachment on sportswear and decorative stitching on fashion garments.",
  max_speed_spm:4500, needle_system:"DB×1", needle_size_range:"9–16",
  manual_url:`${HL}/HIGHLEAD%20CZM200%20instructions%20%26%20parts%20catalog.pdf`, manual_source:"retailer" },

// ══ YAMATO — remaining models ═════════════════════════════════════════════════

{ slug:"yamato-aef-31", brand_slug:"yamato", model_name:"AEF-31", category:"coverstitch",
  description:"Yamato AEF-31 flat-seam machine for underwear and sportswear construction. The AEF series applies the flat-locked seam used in lingerie, swimwear, and performance sportswear.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20AEF-31%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-az6500g-a", brand_slug:"yamato", model_name:"AZ6500G-A", category:"overlock",
  description:"Yamato AZ6500G-A 5-thread safety-stitch overlock for heavy knitwear and outerwear. A more powerful predecessor to the AZ7000G for production sewing of heavy jersey and fleece fabrics.",
  max_speed_spm:7000, needle_system:"DC×27", needle_size_range:"9–14", discontinued:true,
  manual_url:`${YM}/YAMATO%20AZ%206500G-A%20INSTRUCTION%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-fd-62g-20", brand_slug:"yamato", model_name:"FD-62G-20", category:"coverstitch",
  description:"Yamato FD-62G-20 cylinder-arm multi-needle coverstitch for tubular knit hemming. The cylinder arm version of the FD series for hemming tubular knitwear without opening the seam.",
  max_speed_spm:6000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20FD-62G-20%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-mg2002p", brand_slug:"yamato", model_name:"MG2002P", category:"coverstitch",
  description:"Yamato MG2002P multi-needle chain-stitch coverstitch for high-speed knitwear hemming. A high-production coverstitch machine for T-shirts and knitwear hems in high-volume factories.",
  max_speed_spm:7000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20MG2002P%20%20INSTRUCTIONS%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-mg2002pc", brand_slug:"yamato", model_name:"MG2002PC", category:"coverstitch",
  description:"Yamato MG2002PC multi-needle coverstitch with cylinder arm for tubular knit hemming. A cylinder-arm variant of the MG2002P for hemming T-shirts and knitwear without flattening the tube.",
  max_speed_spm:7000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20MG2002PC%20%20INSTRUCTIONS%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-nb2100", brand_slug:"yamato", model_name:"NB2100", category:"coverstitch",
  description:"Yamato NB2100 belt-loop attacher using coverstitch for trouser waistband loop attachment. Combines the coverstitch stitch type with automatic belt-loop feeding and positioning.",
  max_speed_spm:4000, needle_system:"HA×1",
  manual_url:`${YM}/YAMATO%20NB2100%20INSTRUCTION%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-pv-2700", brand_slug:"yamato", model_name:"PV-2700", category:"coverstitch",
  description:"Yamato PV-2700 cylinder-arm coverstitch for tubular garment hemming. The PV series provides coverstitch on a post-bed configuration for hemming in-the-round on tubular knit fabrics.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20PV-2700%20INSTRUCTIONS%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-rs25", brand_slug:"yamato", model_name:"RS25", category:"lockstitch",
  description:"Yamato RS25 single-needle lockstitch for decorative and structural stitching. A specialty Yamato lockstitch machine for applications requiring precise stitch placement and high reliability.",
  max_speed_spm:5000, needle_system:"DB×1", needle_size_range:"9–16",
  manual_url:`${YM}/YAMATO%20RS25%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-sc-10", brand_slug:"yamato", model_name:"SC-10", category:"coverstitch",
  description:"Yamato SC-10 cylinder-arm coverstitch for sock and circular knitwear hemming. A specialized coverstitch for the narrow-diameter tubes in sock and stocking manufacturing.",
  max_speed_spm:5500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20SC-10%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-tg3", brand_slug:"yamato", model_name:"TG3", category:"coverstitch",
  description:"Yamato TG3 multi-needle coverstitch for high-speed T-shirt and underwear hemming. A three-needle coverstitch machine producing the wide coverstitch bands used in premium T-shirt waistbands.",
  max_speed_spm:7000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20TG3%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-ub5", brand_slug:"yamato", model_name:"UB5/UB6", category:"coverstitch",
  description:"Yamato UB5/UB6 flat-seam coverstitch for underwear and swimwear. The UB series applies the smooth flat-locked seam that eliminates chafing in close-fitting underwear and swimwear.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20UB5%2C%20UB6%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-vc2700m-ut", brand_slug:"yamato", model_name:"VC2700M UT", category:"coverstitch",
  description:"Yamato VC2700M UT cylinder-arm coverstitch with under-trimmer for clean tubular hemming. The UT (under-trimmer) cuts the raw edge as it coverstitch-hems tubular knitwear.",
  max_speed_spm:6000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20VC2700M%20UT%20INSTRUCTIONS%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-ves-ut", brand_slug:"yamato", model_name:"VES-UT", category:"coverstitch",
  description:"Yamato VES-UT cylinder-arm coverstitch with under-trimmer for sportswear hemming. A compact cylinder-arm coverstitch specifically designed for active knitwear factories producing sportswear.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20VES-UT%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-ves-ut-a", brand_slug:"yamato", model_name:"VES-UT-A", category:"coverstitch",
  description:"Yamato VES-UT-A cylinder-arm coverstitch with under-trimmer and auto-thread. The A variant adds automatic thread handling for faster setup and consistent trimming results.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20VES-UT-A%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-ves3712-8", brand_slug:"yamato", model_name:"VES3712-8", category:"coverstitch",
  description:"Yamato VES3712-8 cylinder-arm coverstitch with 8mm needle spread for wide coverstitch bands. The 3712-8 produces wider decorative coverstitch bands on knitwear for fashion sportswear.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20VES3712-8%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-vf2429-mc", brand_slug:"yamato", model_name:"VF2429-MC", category:"coverstitch",
  description:"Yamato VF2429-MC cylinder-arm multi-needle coverstitch with chain cutter. The MC (main chain cutter) trims and secures the last stitch chain for clean finishing without tail threads.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20VF2429-MC%20INSTRUCTIONS%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-vfs2513-8", brand_slug:"yamato", model_name:"VFS2513-8", category:"coverstitch",
  description:"Yamato VFS2513-8 cylinder-arm coverstitch with 8mm gauge and built-in spreader. The spreader device catches and lays the fabric edge flat before the coverstitch is applied.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20VFS2513-8%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-vg2790", brand_slug:"yamato", model_name:"VG2790", category:"coverstitch",
  description:"Yamato VG2790 cylinder-arm coverstitch with automatic spreader for knitwear cuff and waistband attachment. The 2790 adds an automatic fabric spreader for more consistent material presentation.",
  max_speed_spm:6000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20VG2790%20%20INSTRUCTIONS%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-vg3721-8-utl", brand_slug:"yamato", model_name:"VG3721-8-UTL/A/Y", category:"coverstitch",
  description:"Yamato VG3721-8 cylinder-arm coverstitch with 8mm gauge, under-trimmer, and long arm for wide tubular goods. The UTL (under-trimmer long) variant handles wider-diameter tubular knitwear.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20VG3721-8-UTL_A_Y%20INSTRUCTIONS%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-vgs3721-8", brand_slug:"yamato", model_name:"VGS3721-8", category:"coverstitch",
  description:"Yamato VGS3721-8 cylinder-arm coverstitch with spreader and 8mm gauge for sportswear hemming. The S (spreader) version automatically opens and presents the knit fabric edge for coverstitch application.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20VGS3721_8%20INSTRUCTIONS%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-vt2502", brand_slug:"yamato", model_name:"VT2502", category:"coverstitch",
  description:"Yamato VT2502 cylinder-arm coverstitch for tubular knitwear hemming. A compact, high-speed cylinder-arm coverstitch for T-shirt and underwear hem finishing in high-volume knitwear factories.",
  max_speed_spm:7000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20VT2502%20INSTRUCTIONS%20AND%20PARTS%20BOOK.pdf`, manual_source:"retailer" },
{ slug:"yamato-ya6500h", brand_slug:"yamato", model_name:"YA 6500H", category:"lockstitch",
  description:"Yamato YA 6500H industrial lockstitch for heavy fabrics and technical textiles. A high-capacity Yamato lockstitch machine for industrial sewing applications requiring heavy thread and needle systems.",
  max_speed_spm:4500, needle_system:"DB×1", needle_size_range:"14–21",
  manual_url:`${YM}/YAMATO%20YA%206500H%20INSTRUCTION%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"yamato-z361", brand_slug:"yamato", model_name:"Z361–Z368", category:"coverstitch",
  description:"Yamato Z361-Z368 multi-needle zigzag coverstitch for decorative and functional knitwear stitching. The Z series applies zigzag-pattern coverstitch for decorative accents and seam finishing on knitwear.",
  max_speed_spm:6000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${YM}/YAMATO%20Z361-Z368%20INSTRUCTION%20MANUAL.pdf`, manual_source:"retailer" },

// ══ KANSAI — remaining models ═════════════════════════════════════════════════

{ slug:"kansai-mac100", brand_slug:"kansai", model_name:"MAC100", category:"lockstitch",
  description:"Kansai MAC100 multi-needle arm-type chainstitch for waistband topstitching. A specialty machine for applying multiple rows of chainstitch on trouser waistbands in a single pass.",
  max_speed_spm:4000, needle_system:"DP×17", needle_size_range:"9–16",
  manual_url:`${KA}/MAC100%28ENG%29.pdf`, manual_source:"retailer" },
{ slug:"kansai-mc30", brand_slug:"kansai", model_name:"MC30", category:"lockstitch",
  description:"Kansai MC30 multi-needle chainstitch for decorative waistband stitching. A compact multi-needle machine for applying closely-spaced chainstitch rows on waistbands and cuffs.",
  max_speed_spm:4000, needle_system:"DP×17", needle_size_range:"9–14",
  manual_url:`${KA}/MC30%28ENG%29.pdf`, manual_source:"retailer" },
{ slug:"kansai-mz-utc", brand_slug:"kansai", model_name:"MZ UTC", category:"lockstitch",
  description:"Kansai MZ UTC multi-needle zigzag with under-thread control for elastic attachment. The UTC mechanism controls lower-thread tension precisely for even zigzag attachment of elastic on waistbands.",
  max_speed_spm:5000, needle_system:"DP×17", needle_size_range:"9–14",
  manual_url:`${KA}/MZ%20UTC%28ENG%29.pdf`, manual_source:"retailer" },
{ slug:"kansai-mz", brand_slug:"kansai", model_name:"MZ", category:"lockstitch",
  description:"Kansai MZ multi-needle zigzag machine for elastic attachment and decorative stitching. The MZ applies multiple zigzag rows simultaneously for waistband elastic and decorative striping.",
  max_speed_spm:5000, needle_system:"DP×17", needle_size_range:"9–14",
  manual_url:`${KA}/MZ%28ENG%29.pdf`, manual_source:"retailer" },
{ slug:"kansai-rx", brand_slug:"kansai", model_name:"RX", category:"lockstitch",
  description:"Kansai RX multi-needle chainstitch for reinforced waistband stitching. The RX series applies dense multi-needle chainstitch for strong, decorative trouser and shorts waistband finishing.",
  max_speed_spm:4500, needle_system:"DP×17", needle_size_range:"9–14",
  manual_url:`${KA}/RX%28ENG%29.pdf`, manual_source:"retailer" },
{ slug:"kansai-rx9701j", brand_slug:"kansai", model_name:"RX9701J", category:"lockstitch",
  description:"Kansai RX9701J specialized multi-needle chainstitch for premium denim waistbands. The 9701J designation indicates a high-speed version with specific thread management for denim waistband production.",
  max_speed_spm:4500, needle_system:"DP×17", needle_size_range:"11–18",
  manual_url:`${KA}/RX9701J%28ENG%29.pdf`, manual_source:"retailer" },
{ slug:"kansai-px301", brand_slug:"kansai", model_name:"PX301-4-3FP", category:"lockstitch",
  description:"Kansai PX301-4-3FP 4-needle chainstitch for fly-piece topstitching on jeans. A specialized machine applying 4 rows of chainstitch for the decorative stitching at the jeans fly opening.",
  max_speed_spm:4000, needle_system:"DP×17", needle_size_range:"11–18",
  manual_url:`${KA}/PX301-4-3FP%28ENG%29.pdf`, manual_source:"retailer" },
{ slug:"kansai-uk", brand_slug:"kansai", model_name:"UK", category:"lockstitch",
  description:"Kansai UK multi-needle chainstitch for denim outseam and inseam topstitching. Applies multiple parallel rows of chainstitch for the decorative and structural seam topstitching on jeans.",
  max_speed_spm:4000, needle_system:"DP×17", needle_size_range:"11–18",
  manual_url:`${KA}/UK_ENG_1.pdf`, manual_source:"retailer" },
{ slug:"kansai-fx", brand_slug:"kansai", model_name:"FX", category:"lockstitch",
  description:"Kansai FX multi-needle chainstitch for general waistband and cuff stitching. The standard Kansai FX (without UTC) for lighter-duty multi-needle topstitching applications.",
  max_speed_spm:5000, needle_system:"DP×17", needle_size_range:"9–14",
  manual_url:`${KA}/FX%28ENG%29.pdf`, manual_source:"retailer" },
{ slug:"kansai-dx", brand_slug:"kansai", model_name:"DX", category:"lockstitch",
  description:"Kansai DX multi-needle chainstitch for dense close-pitch topstitching. Applies very closely-spaced needle rows for ultra-fine decorative stitching on premium denim and fashion garments.",
  max_speed_spm:5000, needle_system:"DP×17", needle_size_range:"9–14",
  manual_url:`${KA}/DX%28ENG%29.pdf`, manual_source:"retailer" },
{ slug:"kansai-blx", brand_slug:"kansai", model_name:"BLX", category:"lockstitch",
  description:"Kansai BLX multi-needle chainstitch for wide-band belt-loop and waistband attachment. The BLX produces wider stitch bands than the standard BX for heavier belt loops and reinforced waistbands.",
  max_speed_spm:4500, needle_system:"DP×17", needle_size_range:"11–18",
  manual_url:`${S3}/KANSAI-PDF/KAN-BLX-INST.pdf`, manual_source:"retailer" },
{ slug:"kansai-lx5801sp", brand_slug:"kansai", model_name:"LX5801SP", category:"lockstitch",
  description:"Kansai LX5801SP long-arm multi-needle chainstitch for wide-panel decorative stitching. The LX long arm provides extra clearance for multi-needle topstitching on wide trouser legs and panel seams.",
  max_speed_spm:4000, needle_system:"DP×17", needle_size_range:"9–16",
  manual_url:`${S3}/KANSAI-PDF/KAN-LX5801SP-INST.pdf`, manual_source:"retailer" },

// ══ PEGASUS — remaining models ════════════════════════════════════════════════

{ slug:"pegasus-bt-m700", brand_slug:"pegasus", model_name:"BT-M700", category:"coverstitch",
  description:"Pegasus BT-M700 bed-type cylinder-arm coverstitch for T-shirt and knitwear hemming. A bed-type variant of the M700 cylinder-arm coverstitch for wider-diameter tubular knitwear.",
  max_speed_spm:5500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${PG}/BT-M700-INST.pdf`, manual_source:"retailer" },
{ slug:"pegasus-e-52", brand_slug:"pegasus", model_name:"E-52", category:"overlock",
  description:"Pegasus E-52 high-speed 5-thread safety-stitch overlock for lightweight knitwear. A specialized Pegasus overlock for fine jersey and delicate knit fabric edge finishing.",
  max_speed_spm:7000, needle_system:"DC×27", needle_size_range:"9–14",
  manual_url:`${PG}/E-52-INST.PDF`, manual_source:"retailer" },
{ slug:"pegasus-ex-series", brand_slug:"pegasus", model_name:"EX Series", category:"overlock",
  description:"Pegasus EX Series industrial overlock for high-speed knitwear production. The EX series represents Pegasus's premium overlock range with highest stitch quality and lowest noise levels.",
  max_speed_spm:8000, needle_system:"DC×27", needle_size_range:"9–14",
  manual_url:`${PI}/EX-SERIES-INST.pdf`, manual_source:"retailer" },
{ slug:"pegasus-ext-series", brand_slug:"pegasus", model_name:"EXT Series", category:"overlock",
  description:"Pegasus EXT Series overlock with extended differential feed for extreme stretch fabrics. The EXT adapts the EX series for high-stretch fabrics like elastane blends and performance knitwear.",
  max_speed_spm:8000, needle_system:"DC×27", needle_size_range:"9–14",
  manual_url:`${PI}/EXT-SERIES-INST.pdf`, manual_source:"retailer" },
{ slug:"pegasus-516-4", brand_slug:"pegasus", model_name:"516-4", category:"overlock",
  description:"Pegasus 516-4 4-thread overlock for knitwear seaming and overlocking. A 4-thread overlock that provides stronger seaming than 3-thread for knitwear and stretch fabric garments.",
  max_speed_spm:7000, needle_system:"DC×27", needle_size_range:"9–14",
  manual_url:`${PG}/PEG-516-4-INST.PDF`, manual_source:"retailer" },
{ slug:"pegasus-e32", brand_slug:"pegasus", model_name:"E32", category:"overlock",
  description:"Pegasus E32 industrial overlock for standard knitwear production. A versatile mid-range Pegasus overlock for general-purpose knitwear seaming and edge finishing.",
  max_speed_spm:7000, needle_system:"DC×27", needle_size_range:"9–14",
  manual_url:`${PG}/PEG-E32-INST.pdf`, manual_source:"retailer" },
{ slug:"pegasus-l52", brand_slug:"pegasus", model_name:"L52 Series", category:"overlock",
  description:"Pegasus L52 Series industrial overlock with special thread delivery for consistent tension. A precision overlock for high-quality knitwear finishing in premium garment production.",
  max_speed_spm:7500, needle_system:"DC×27", needle_size_range:"9–14",
  manual_url:`${PG}/PEG-L52-SERIES-INST.pdf`, manual_source:"retailer" },
{ slug:"pegasus-mc401", brand_slug:"pegasus", model_name:"MC401", category:"coverstitch",
  description:"Pegasus MC401 cylinder-arm multi-needle coverstitch for circular knitwear hemming. A specialized coverstitch machine for sewing in-the-round on T-shirts and underwear without flattening the tube.",
  max_speed_spm:6000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${PG}/PEG-MC401-INST.pdf`, manual_source:"retailer" },

// ══ BROTHER — remaining models ════════════════════════════════════════════════

{ slug:"brother-bas-416a", brand_slug:"brother", model_name:"BAS-416A", category:"lockstitch",
  description:"Brother BAS-416A programmable cycle sewing machine with electronic in-process inspection. The 416A adds automated seam quality checking during the sewing cycle for zero-defect production.",
  max_speed_spm:2700, needle_system:"DB×1",
  manual_url:`${BR}/BAS-416A%2CBES-1210AC%20INSTRUCTIONS.PDF`, manual_source:"retailer" },
{ slug:"brother-be-438fx", brand_slug:"brother", model_name:"BE-438FX", category:"lockstitch",
  description:"Brother BE-438FX electronic lockstitch with feed-off-the-arm mechanism for knitwear side seams. A specialized machine combining the precision of a programmable lockstitch with FOTA feed for knitwear.",
  max_speed_spm:5000, needle_system:"DB×1", needle_size_range:"9–16",
  manual_url:`${BR}/BE-438FX%20INSTRUCTIONS.pdf`, manual_source:"retailer" },
{ slug:"brother-dt6-b928", brand_slug:"brother", model_name:"DT6-B928", category:"lockstitch",
  description:"Brother DT6-B928 direct-drive industrial lockstitch with 6-step feed adjustment. The 6-step feed system allows fine-tuning of fabric advancement for different material types and thicknesses.",
  max_speed_spm:5500, needle_system:"DB×1", needle_size_range:"9–18",
  manual_url:`${BR}/DT6-B928%20instruction%20manuel.pdf`, manual_source:"retailer" },
{ slug:"brother-ef4-b531", brand_slug:"brother", model_name:"EF4-B531", category:"coverstitch",
  description:"Brother EF4-B531 multi-needle coverstitch with extended needle configurations for wide band hemming. An expanded-needle-count version of the EF4-B511 for wider hem bands on sportswear.",
  max_speed_spm:6000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${BR}/EF4-B511%2C%20B531%2C%20INSTRUCTIONS.PDF`, manual_source:"retailer" },
{ slug:"brother-ef4-b571", brand_slug:"brother", model_name:"EF4-B571", category:"coverstitch",
  description:"Brother EF4-B571 multi-needle coverstitch with spreader device for automatic knitwear edge presentation. The integrated spreader opens the knit fabric edge before the coverstitch is applied.",
  max_speed_spm:6000, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${BR}/EF4-B561%2C%20B571%2C%20MA4-B581%20INSTRUCTIONS.pdf`, manual_source:"retailer" },
{ slug:"brother-fa-v81a", brand_slug:"brother", model_name:"FA-V81A", category:"coverstitch",
  description:"Brother FA-V81A cylinder-arm coverstitch with IoT connectivity for high-speed knitwear production. A networked coverstitch machine for factory-wide production monitoring and quality tracking.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${BR}/FA-V72A%2CV82A%2C%2092A%20INSTRUCTIONS.PDF`, manual_source:"retailer" },
{ slug:"brother-ma4-b600", brand_slug:"brother", model_name:"MA4-B600", category:"coverstitch",
  description:"Brother MA4-B600 multi-needle coverstitch for high-speed T-shirt and knitwear hemming. An upgraded coverstitch platform from Brother with improved thread delivery for higher stitch quality.",
  max_speed_spm:6500, needle_system:"HA×1", needle_size_range:"9–14",
  manual_url:`${BR}/EF4%26MA4-B600-INST.pdf`, manual_source:"retailer" },
{ slug:"brother-lk3-b434e", brand_slug:"brother", model_name:"LK3-B434E MK2", category:"lockstitch",
  description:"Brother LK3-B434E MK2 electronic bar tacker with improved control system. A next-generation electronic bar tacker with updated programming interface for faster setup and more pattern options.",
  max_speed_spm:3500, needle_system:"DP×5",
  manual_url:`${BR}/BROTHER-BROCHURES/lk3-b434e%20MK2%20instruction.pdf`, manual_source:"retailer" },

// ══ CONSEW — final remaining models ═══════════════════════════════════════════

{ slug:"consew-227r-1", brand_slug:"consew", model_name:"227R-1", category:"walking-foot",
  description:"Consew 227R-1 compound-feed walking-foot lockstitch for medium leather and vinyl upholstery. A reliable entry-level walking-foot machine for production sewing of leather goods and vinyl upholstery.",
  max_speed_spm:2500, needle_system:"135×17", needle_size_range:"14–18",
  manual_url:`${CN}/CONSEW%20227R-1%20INTRUCTION%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"consew-227r-2", brand_slug:"consew", model_name:"227R-2", category:"walking-foot",
  description:"Consew 227R-2 compound-feed walking-foot for medium-heavy leather and vinyl. An updated 227R with improved feed mechanism for consistent seaming on a wider range of material thicknesses.",
  max_speed_spm:2500, needle_system:"135×17", needle_size_range:"14–21",
  manual_url:`${CN}/CONSEW%20227R-2%20INSTRUCTION%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"consew-2457r-1a", brand_slug:"consew", model_name:"2457R-1A", category:"walking-foot",
  description:"Consew 2457R-1A compound-feed walking-foot for heavy material production. A heavy-duty walking-foot machine combining compound feed with a large hook for thick thread and material.",
  max_speed_spm:2200, needle_system:"135×17", needle_size_range:"16–23",
  manual_url:`${CN}/CONSEW%202457R-1A%20INSTRUCTION%20MANUAL.pdf`, manual_source:"retailer" },
{ slug:"consew-328r-1", brand_slug:"consew", model_name:"328R-1", category:"walking-foot",
  description:"Consew 328R-1 heavy compound-feed walking-foot for industrial canvas. An industrial canvas machine from the Consew 328R series with improved stitching control for thick synthetic canvas.",
  max_speed_spm:2000, needle_system:"135×17", needle_size_range:"18–25",
  manual_url:`${CO}/CONSEW%20328R-1%20OPERATING%20INSTRUCTIONS.pdf`, manual_source:"retailer" },
{ slug:"consew-555h", brand_slug:"consew", model_name:"555H", category:"walking-foot",
  description:"Consew 555H compound-feed walking-foot for extreme-heavy industrial applications. One of Consew's heaviest flatbed walking-foot machines for sewing fire hose, conveyor belts, and military canvas.",
  max_speed_spm:1200, needle_system:"794 H", needle_size_range:"25–35",
  manual_url:`${CO}/CONSEW%20555H%20INSTRUCTION%20MANUAL.pdf`, manual_source:"retailer" },

// ══ SINGER — final more models ════════════════════════════════════════════════

{ slug:"singer-71-w-series", brand_slug:"singer", model_name:"71W Series", category:"overlock",
  description:"Singer Class 71W walking-foot FOTA chainstitch overlock. The W variants of the Singer 71 series add walking-foot feed to the FOTA chainstitch for sewing through multiple thick knit layers.",
  max_speed_spm:5000, needle_system:"UY×128", needle_size_range:"9–14", discontinued:true,
  manual_url:`${SI}/71W1_W2_W3.pdf`, manual_source:"retailer" },
{ slug:"singer-95-40", brand_slug:"singer", model_name:"95-40 Series", category:"lockstitch",
  description:"Singer Class 95-40 series industrial lockstitch for mid-weight fabric sewing. More specific variants in the 95 series with refinements for particular fabric types and seam applications.",
  max_speed_spm:3500, needle_system:"135×17", needle_size_range:"11–18", discontinued:true,
  manual_url:`${SI}/95-40_60.pdf`, manual_source:"retailer" },
{ slug:"singer-96-10-series", brand_slug:"singer", model_name:"96-10 Series", category:"lockstitch",
  description:"Singer Class 96-10 series industrial lockstitch variants. Mid-century Singer 96 variants with different stitch mechanisms for specific industrial sewing applications.",
  max_speed_spm:3500, needle_system:"135×17", needle_size_range:"9–16", discontinued:true,
  manual_url:`${SI}/96-10_12_16.pdf`, manual_source:"retailer" },
{ slug:"singer-96-80-series", brand_slug:"singer", model_name:"96-80 Series", category:"lockstitch",
  description:"Singer Class 96-80 series industrial lockstitch for heavy fabrics. Later 96 class variants with improved needle bar and feed mechanisms for heavier industrial sewing.",
  max_speed_spm:4000, needle_system:"135×17", needle_size_range:"11–21", discontinued:true,
  manual_url:`${SI}/96-80_100.pdf`, manual_source:"retailer" },
{ slug:"singer-96-87-series", brand_slug:"singer", model_name:"96-87 Series", category:"lockstitch",
  description:"Singer Class 96-87 series lockstitch. Later variants in the Singer 96 series for production sewing of medium to heavy fabrics in industrial settings.",
  max_speed_spm:4000, needle_system:"135×17", needle_size_range:"11–21", discontinued:true,
  manual_url:`${SI}/96-87_107.pdf`, manual_source:"retailer" },
{ slug:"singer-99w-series", brand_slug:"singer", model_name:"99W110–113", category:"walking-foot",
  description:"Singer Class 99W FOTA chainstitch series for medium knitwear seaming. The 99W group covering models 110 through 113 for various knitwear weights and seam types.",
  max_speed_spm:5000, needle_system:"UY×128", needle_size_range:"9–14", discontinued:true,
  manual_url:`${SI}/99W110_111_112_113.pdf`, manual_source:"retailer" },

];

async function run() {
  const brandIds: Record<string, string> = {};
  const { data: existing } = await db.from("brands").select("id, slug");
  for (const b of (existing ?? []) as { id: string; slug: string }[]) brandIds[b.slug] = b.id;

  console.log("── Machines ──");
  let ok = 0;
  for (const m of MACHINES) {
    const brand_id = brandIds[m.brand_slug];
    if (!brand_id) { console.error(`  ✗ ${m.slug}: brand '${m.brand_slug}' not found`); continue; }
    const { slug, brand_slug: _, ...rest } = m;
    const { error } = await db.from("machines").upsert({ slug, brand_id, ...rest }, { onConflict: "slug" });
    if (error) console.error(`  ✗ ${slug}:`, error.message);
    else { process.stdout.write("."); ok++; }
  }

  const { count } = await db.from("machines").select("*", { count: "exact", head: true });
  console.log(`\n\nDone: ${ok}/${MACHINES.length}. Total in DB: ${count}`);
}
run().catch(e => { console.error(e); process.exit(1); });
