import { readFileSync } from "fs";
import { resolve } from "path";
try {
  const envFile = readFileSync(resolve(process.cwd(), ".env.local"), "utf8");
  for (const line of envFile.split("\n")) {
    const m = line.match(/^([^#=]+)=(.*)$/);
    if (m) process.env[m[1].trim()] = m[2].trim();
  }
} catch { /* ignore */ }

import { createClient } from "@supabase/supabase-js";
const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });

async function run() {
  // ── NEW BRANDS ──────────────────────────────────────────────────────────────
  console.log("Adding new brands…");
  const { data: newBrands, error: bErr } = await db.from("brands").upsert([
    { name: "Yamato", slug: "yamato", description: "Japanese specialist in coverstitch, flatseamer, and overlock machines. Yamato invented the coverstitch machine and remains the benchmark for the t-shirt and sportswear industry.", country: "Japan", website_url: "https://www.yamato-co.jp" },
    { name: "Pegasus", slug: "pegasus", description: "Japanese manufacturer of overlock, coverstitch, and flatseamer machines. Used in premium knitwear, denim, and sportswear factories globally.", country: "Japan", website_url: "https://www.pegasus.co.jp" },
    { name: "Jack Sewing Machine", slug: "jack", description: "China's largest sewing machine manufacturer. Jack machines offer modern direct-drive technology at competitive prices and are increasingly used in professional garment factories worldwide.", country: "China", website_url: "https://www.jack-sewing.com" },
    { name: "Pfaff Industrial", slug: "pfaff", description: "German manufacturer known for precision lockstitch and compound-feed machines. Pfaff 1245 and 545 are standards in leather goods, automotive, and heavy canvas industries.", country: "Germany", website_url: "https://www.pfaff.com" },
    { name: "Dürkopp Adler", slug: "durkopp-adler", description: "German manufacturer of heavy-duty industrial sewing machines for leather, shoes, bags, and automotive upholstery. Benchmarks for durability and precision.", country: "Germany", website_url: "https://www.duerkopp-adler.com" },
  ], { onConflict: "slug" }).select("id,slug");
  if (bErr) { console.error("brands:", bErr); process.exit(1); }

  // Fetch ALL brand IDs including original ones
  const { data: allBrands } = await db.from("brands").select("id,slug");
  const bid = Object.fromEntries((allBrands ?? []).map((b: { id: string; slug: string }) => [b.slug, b.id]));
  console.log("All brands:", Object.keys(bid));

  // ── EXTRA JUKI MODELS ───────────────────────────────────────────────────────
  const moreJuki = [
    { brand_id: bid.juki, model_name: "Juki DDL-900A", slug: "juki-ddl-900a", category: "lockstitch", description: "Direct-drive lockstitch machine with servo motor built into the machine head. Silent, energy-efficient, and requires no belt — ideal for small studios and factories.", max_speed_spm: 5000, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Juki large hook (class)", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: "https://www.juki.com/sewing/en/products/industrial/lockstitch/", manual_source: "manufacturer", discontinued: false, year_introduced: 2018 },
    { brand_id: bid.juki, model_name: "Juki LH-3568A", slug: "juki-lh-3568a", category: "lockstitch", description: "Twin-needle lockstitch machine producing two parallel rows of stitching simultaneously. Standard for belt loops, pocket openings, and waistband attachment in jeans manufacturing.", max_speed_spm: 5000, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Juki twin hook", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2005 },
    { brand_id: bid.juki, model_name: "Juki LZ-2290A-SR", slug: "juki-lz-2290a-sr", category: "other", description: "Electronic zigzag lockstitch machine. Used for buttonholes, bar tacks, and decorative stitching on sportswear and leather goods.", max_speed_spm: 4000, stitch_length_max: 4.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Juki large hook (class)", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2010 },
    { brand_id: bid.juki, model_name: "Juki MO-6816S", slug: "juki-mo-6816s", category: "overlock", description: "High-speed 5/6-thread safety-stitch overlock. Combines a 4-thread overlock with a 2-thread chain stitch for maximum seam strength on heavy knitwear.", max_speed_spm: 8500, stitch_length_max: 4.0, needle_system: "DCx27 (ELx705)", needle_size_range: "#9–#16 (Nm 65–100)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2014 },
    { brand_id: bid.juki, model_name: "Juki MS-1261", slug: "juki-ms-1261", category: "coverstitch", description: "2-needle 4-thread flatseamer. Creates the flat-locked seam seen on athletic wear, swimwear, and outdoor gear where bulk must be minimised.", max_speed_spm: 6500, stitch_length_max: 4.0, needle_system: "UYx128GAS", needle_size_range: "#11–#16 (Nm 75–100)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2008 },
    { brand_id: bid.juki, model_name: "Juki TNU-243U", slug: "juki-tnu-243u", category: "post-bed", description: "Post-bed unison-feed lockstitch machine. The vertical post arm stitches on tubular items, boot shafts, bags, and shoe uppers that cannot be placed on a flat bed.", max_speed_spm: 2500, stitch_length_max: 9.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Juki large hook (class)", presser_foot_height: 13.0, lift_height_max: 16.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2004 },
    { brand_id: bid.juki, model_name: "Juki AMS-210EN", slug: "juki-ams-210en", category: "other", description: "Computer-controlled cycle sewing machine (pattern tacker). Sews preset stitch patterns for pockets, labels, belt loops, and logos automatically. No operator skill needed for consistent results.", max_speed_spm: 3000, stitch_length_max: null, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#16 (Nm 65–100)", bobbin_type: "Juki large hook (class)", presser_foot_height: null, lift_height_max: null, manual_url: "https://www.juki.com/sewing/en/products/industrial/electronicsewing/", manual_source: "manufacturer", discontinued: false, year_introduced: 2012 },
    { brand_id: bid.juki, model_name: "Juki LBH-1790", slug: "juki-lbh-1790", category: "buttonhole", description: "Computer-controlled buttonhole machine. Sews up to 40 preset buttonhole shapes with automatic thread trimming. Industry standard for shirts, jackets, and trousers.", max_speed_spm: 3200, stitch_length_max: null, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#14 (Nm 65–90)", bobbin_type: "Juki large hook (class)", presser_foot_height: null, lift_height_max: null, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2010 },
  ];

  // ── EXTRA CONSEW MODELS ─────────────────────────────────────────────────────
  const moreConsew = [
    { brand_id: bid.consew, model_name: "Consew 2101", slug: "consew-2101", category: "lockstitch", description: "High-speed single-needle lockstitch for light to medium garment sewing. The 2101 is Consew's core production-floor lockstitch, competitive with the Juki DDL-8700.", max_speed_spm: 5500, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Consew large hook", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2000 },
    { brand_id: bid.consew, model_name: "Consew 225", slug: "consew-225", category: "lockstitch", description: "Classic Consew lockstitch machine for medium to heavy-weight fabrics. Popular in upholstery and canvas shops that also do some flat sewing.", max_speed_spm: 4500, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#14–#21 (Nm 90–130)", bobbin_type: "Consew large hook", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1975 },
    { brand_id: bid.consew, model_name: "Consew 320RB-1", slug: "consew-320rb-1", category: "walking-foot", description: "Compound-feed walking-foot machine for automotive upholstery, marine canvas, and heavy leather. The triple feed eliminates slippage on non-porous materials.", max_speed_spm: 2000, stitch_length_max: 10.0, needle_system: "DPx5 (135x17)", needle_size_range: "#18–#24 (Nm 110–160)", bobbin_type: "Consew large hook", presser_foot_height: 16.0, lift_height_max: 18.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1998 },
    { brand_id: bid.consew, model_name: "Consew CP206RLB-1A", slug: "consew-cp206rlb-1a", category: "walking-foot", description: "Walking-foot machine with table and servo motor package — a complete sewing station ready for production. Popular with small upholstery shops buying a first industrial machine.", max_speed_spm: 2500, stitch_length_max: 10.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Consew large hook", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2010 },
  ];

  // ── EXTRA BROTHER MODELS ────────────────────────────────────────────────────
  const moreBrother = [
    { brand_id: bid.brother, model_name: "Brother S-7200C", slug: "brother-s7200c", category: "lockstitch", description: "High-speed direct-drive lockstitch with automatic thread trimming, backtacking, and presser foot lifter. Brother's answer to the Juki DDL-9000C.", max_speed_spm: 5000, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Brother large hook", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: "https://www.brother.com/en/sewing_products/industrial", manual_source: "manufacturer", discontinued: false, year_introduced: 2016 },
    { brand_id: bid.brother, model_name: "Brother DA-9270-H", slug: "brother-da9270h", category: "walking-foot", description: "High-speed unison-feed lockstitch machine for leather, denim, and automotive materials. Direct drive eliminates clutch motor maintenance.", max_speed_spm: 2500, stitch_length_max: 9.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Brother large hook", presser_foot_height: 13.0, lift_height_max: 16.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2018 },
    { brand_id: bid.brother, model_name: "Brother EF4-B231", slug: "brother-ef4-b231", category: "coverstitch", description: "3-needle coverstitch for t-shirt and sportswear hemming. Compact footprint for factory production lines.", max_speed_spm: 6000, stitch_length_max: 4.0, needle_system: "UYx128GAS", needle_size_range: "#11–#16 (Nm 75–100)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2010 },
  ];

  // ── YAMATO ──────────────────────────────────────────────────────────────────
  const yamato = [
    { brand_id: bid.yamato, model_name: "Yamato VF2500D", slug: "yamato-vf2500d", category: "coverstitch", description: "The industry standard 2-needle 4-thread flatseamer. Used in virtually every denim and sportswear factory for inseam and side-seam flat-locking. Extremely fast with a large fabric clearance under the foot.", max_speed_spm: 6500, stitch_length_max: 4.0, needle_system: "UYx128GAS", needle_size_range: "#11–#18 (Nm 75–110)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: "https://www.yamato-co.jp/products/", manual_source: "manufacturer", discontinued: false, year_introduced: 1995 },
    { brand_id: bid.yamato, model_name: "Yamato AZ8450H", slug: "yamato-az8450h", category: "overlock", description: "5-thread safety-stitch overlock for high-strength seams on heavy fabrics like denim, canvas, and fleece. The combination stitch provides both an overlock edge and a chainstitched seam in one pass.", max_speed_spm: 7000, stitch_length_max: 4.0, needle_system: "DCx27 (ELx705)", needle_size_range: "#9–#16 (Nm 65–100)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2000 },
    { brand_id: bid.yamato, model_name: "Yamato VG3700D", slug: "yamato-vg3700d", category: "coverstitch", description: "3-needle 5-thread coverstitch machine. Produces a wider coverstitch band used on waistbands, cuffs, and hems on activewear and underwear.", max_speed_spm: 6000, stitch_length_max: 4.0, needle_system: "UYx128GAS", needle_size_range: "#11–#16 (Nm 75–100)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2002 },
    { brand_id: bid.yamato, model_name: "Yamato VC2700", slug: "yamato-vc2700", category: "coverstitch", description: "Single-needle coverstitch (top-cover stitch) machine. Creates the single-needle hem seen on T-shirt sleeves and activewear hem tape applications.", max_speed_spm: 5500, stitch_length_max: 4.0, needle_system: "UYx128GAS", needle_size_range: "#11–#14 (Nm 75–90)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2005 },
    { brand_id: bid.yamato, model_name: "Yamato DCZ-561", slug: "yamato-dcz-561", category: "overlock", description: "Differential-feed 4-thread overlock for knits and wovens. The adjustable differential feed eliminates puckering on stretch fabrics and waves on wovens.", max_speed_spm: 7500, stitch_length_max: 4.0, needle_system: "DCx27 (ELx705)", needle_size_range: "#9–#14 (Nm 65–90)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2008 },
    { brand_id: bid.yamato, model_name: "Yamato ZF3500D", slug: "yamato-zf3500d", category: "coverstitch", description: "High-speed 2-needle coverstitch for swimwear and lingerie. Handles very fine elastic and nylon fabrics that standard coverstitch machines tend to pucker.", max_speed_spm: 6000, stitch_length_max: 3.5, needle_system: "UYx128GAS", needle_size_range: "#9–#11 (Nm 65–75)", bobbin_type: null, presser_foot_height: 5.0, lift_height_max: 5.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2010 },
  ];

  // ── PEGASUS ──────────────────────────────────────────────────────────────────
  const pegasus = [
    { brand_id: bid.pegasus, model_name: "Pegasus W600P-01CB", slug: "pegasus-w600p", category: "coverstitch", description: "2-needle 4-thread flatseamer, Pegasus's most popular coverstitch machine. Used for denim inseams, activewear side seams, and T-shirt hems worldwide. Competes directly with the Yamato VF2500D.", max_speed_spm: 6500, stitch_length_max: 4.0, needle_system: "UYx128GAS", needle_size_range: "#11–#18 (Nm 75–110)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: "https://www.pegasus.co.jp/products/", manual_source: "manufacturer", discontinued: false, year_introduced: 1998 },
    { brand_id: bid.pegasus, model_name: "Pegasus EX5114-02", slug: "pegasus-ex5114", category: "overlock", description: "4-thread overlock with easy rethreading system. The looper-threading colour guide makes set-up fast for operators in high-turnover production environments.", max_speed_spm: 7500, stitch_length_max: 4.0, needle_system: "DCx27 (ELx705)", needle_size_range: "#9–#14 (Nm 65–90)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2005 },
    { brand_id: bid.pegasus, model_name: "Pegasus W562-01CB", slug: "pegasus-w562", category: "coverstitch", description: "2-needle 4-thread coverstitch for top-cover hemming. The W562 targets medium-weight jersey and interlock fabrics in T-shirt and underwear manufacturing.", max_speed_spm: 6000, stitch_length_max: 4.0, needle_system: "UYx128GAS", needle_size_range: "#11–#16 (Nm 75–100)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2002 },
    { brand_id: bid.pegasus, model_name: "Pegasus WT600P", slug: "pegasus-wt600p", category: "coverstitch", description: "3-needle 5-thread flatseamer for wide flat-lock seams. Used in outdoor and technical garments where strength and flat seam profile are both required.", max_speed_spm: 6000, stitch_length_max: 4.0, needle_system: "UYx128GAS", needle_size_range: "#11–#16 (Nm 75–100)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2006 },
    { brand_id: bid.pegasus, model_name: "Pegasus MX5114", slug: "pegasus-mx5114", category: "overlock", description: "Air-threading 4-thread overlock. One button pressurises air to thread all the loopers automatically — cuts thread change time from 5 minutes to under 30 seconds.", max_speed_spm: 7000, stitch_length_max: 4.0, needle_system: "DCx27 (ELx705)", needle_size_range: "#9–#14 (Nm 65–90)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2014 },
  ];

  // ── JACK ──────────────────────────────────────────────────────────────────────
  const jack = [
    { brand_id: bid.jack, model_name: "Jack A4", slug: "jack-a4", category: "lockstitch", description: "Jack's most popular direct-drive lockstitch machine. Servo motor built in to the head, automatic thread trimming, and a touchscreen control panel. Competes with the Juki DDL-9000C at roughly half the price.", max_speed_spm: 5000, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Large hook (class)", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: "https://www.jack-sewing.com/product/", manual_source: "manufacturer", discontinued: false, year_introduced: 2016 },
    { brand_id: bid.jack, model_name: "Jack A3", slug: "jack-a3", category: "lockstitch", description: "Entry-level direct-drive lockstitch with automatic thread trimming. Widely used in small to medium garment factories in Asia and increasingly in Europe and the US.", max_speed_spm: 4500, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Large hook (class)", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2014 },
    { brand_id: bid.jack, model_name: "Jack C4", slug: "jack-c4", category: "lockstitch", description: "Cylinder-bed direct-drive lockstitch with needle feed. The round bed sews on shoes, bags, boots, and gloves — Jack's answer to the Juki TNU post-bed for cylinder work.", max_speed_spm: 3500, stitch_length_max: 6.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#11–#21 (Nm 75–130)", bobbin_type: "Large hook (class)", presser_foot_height: 13.0, lift_height_max: 14.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2016 },
    { brand_id: bid.jack, model_name: "Jack W4", slug: "jack-w4", category: "walking-foot", description: "Compound-feed walking-foot machine for leather, canvas, and multi-layer materials. Direct drive makes it quieter and more efficient than older clutch motor machines.", max_speed_spm: 2500, stitch_length_max: 10.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Large hook (class)", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2018 },
    { brand_id: bid.jack, model_name: "Jack E4", slug: "jack-e4", category: "lockstitch", description: "High-speed lockstitch with programmable thread trimming, backtacking, and a colour touchscreen. Among the most feature-rich budget industrial machines available.", max_speed_spm: 5500, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Large hook (class)", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2019 },
    { brand_id: bid.jack, model_name: "Jack 803", slug: "jack-803", category: "overlock", description: "High-speed 5-thread overlock machine. Jack's entry-level serger for garment factory production lines, offering a low cost of entry with reliable performance.", max_speed_spm: 7000, stitch_length_max: 4.0, needle_system: "DCx27 (ELx705)", needle_size_range: "#9–#14 (Nm 65–90)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2015 },
    { brand_id: bid.jack, model_name: "Jack JK-T1377", slug: "jack-jk-t1377", category: "walking-foot", description: "Triple-feed compound walking-foot machine for heavy leather, harness, and safety equipment. Jack's heavy-duty offering, competing with the Consew 339RB.", max_speed_spm: 1800, stitch_length_max: 12.0, needle_system: "DPx17 (794)", needle_size_range: "#19–#25 (Nm 120–160)", bobbin_type: "Large hook (class)", presser_foot_height: 18.0, lift_height_max: 20.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2020 },
  ];

  // ── PFAFF INDUSTRIAL ─────────────────────────────────────────────────────────
  const pfaff = [
    { brand_id: bid.pfaff, model_name: "Pfaff 1245", slug: "pfaff-1245", category: "walking-foot", description: "The legendary German compound-feed walking-foot machine. The 1245 is widely considered the world's finest production-grade heavy-duty machine for leather, saddlery, footwear, and automotive upholstery. Built to a standard rarely seen in industrial machinery.", max_speed_spm: 2000, stitch_length_max: 12.0, needle_system: "DPx17 (794)", needle_size_range: "#19–#25 (Nm 120–160)", bobbin_type: "Pfaff hook (large)", presser_foot_height: 18.0, lift_height_max: 22.0, manual_url: "https://www.manualslib.com/search/?q=Pfaff+1245", manual_source: "manualslib", discontinued: false, year_introduced: 1970 },
    { brand_id: bid.pfaff, model_name: "Pfaff 545", slug: "pfaff-545", category: "walking-foot", description: "Pfaff's mid-range compound-feed machine for medium to heavy materials. Long-running model trusted by saddlers and leatherworkers for its smooth feed and consistent tension.", max_speed_spm: 2500, stitch_length_max: 10.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Pfaff hook (medium)", presser_foot_height: 14.0, lift_height_max: 16.0, manual_url: "https://www.manualslib.com/search/?q=Pfaff+545", manual_source: "manualslib", discontinued: false, year_introduced: 1980 },
    { brand_id: bid.pfaff, model_name: "Pfaff 918", slug: "pfaff-918", category: "lockstitch", description: "Classic German precision lockstitch machine for medium fabrics. The Pfaff 918 was widely used in European tailoring and knitwear production throughout the late 20th century.", max_speed_spm: 4500, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Pfaff hook (standard)", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: "https://www.manualslib.com/search/?q=Pfaff+918", manual_source: "manualslib", discontinued: true, year_introduced: 1968 },
    { brand_id: bid.pfaff, model_name: "Pfaff 3811", slug: "pfaff-3811", category: "post-bed", description: "German post-bed lockstitch machine for boots, bags, and shoe uppers. The tall vertical post arm reaches areas inaccessible to flat-bed machines, with typical German build quality.", max_speed_spm: 2500, stitch_length_max: 9.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Pfaff hook (large)", presser_foot_height: 14.0, lift_height_max: 16.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1990 },
    { brand_id: bid.pfaff, model_name: "Pfaff 591", slug: "pfaff-591", category: "lockstitch", description: "Heavy-duty lockstitch for denim, canvas, and multi-layer materials. The 591 series was Pfaff's production workhorse for heavy garments and workwear throughout the 1970s–1990s.", max_speed_spm: 4000, stitch_length_max: 6.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#14–#21 (Nm 90–130)", bobbin_type: "Pfaff hook (large)", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: "https://www.manualslib.com/search/?q=Pfaff+591", manual_source: "manualslib", discontinued: true, year_introduced: 1972 },
  ];

  // ── DÜRKOPP ADLER ────────────────────────────────────────────────────────────
  const durkopp = [
    { brand_id: bid["durkopp-adler"], model_name: "Dürkopp Adler 204-374040", slug: "durkopp-adler-204", category: "lockstitch", description: "German precision lockstitch machine for light to medium garments. Dürkopp Adler's standard production-floor lockstitch, known for extremely quiet operation and long service life.", max_speed_spm: 5000, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "DA large hook", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: "https://www.duerkopp-adler.com/en/service/manuals/", manual_source: "manufacturer", discontinued: false, year_introduced: 2005 },
    { brand_id: bid["durkopp-adler"], model_name: "Dürkopp Adler 274", slug: "durkopp-adler-274", category: "walking-foot", description: "Heavy-duty compound-feed machine for leather handbags, belts, footwear, and automotive components. A benchmark for the European luxury goods industry.", max_speed_spm: 2000, stitch_length_max: 10.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "DA large hook", presser_foot_height: 14.0, lift_height_max: 16.0, manual_url: "https://www.duerkopp-adler.com/en/service/manuals/", manual_source: "manufacturer", discontinued: false, year_introduced: 2000 },
    { brand_id: bid["durkopp-adler"], model_name: "Dürkopp Adler 669", slug: "durkopp-adler-669", category: "post-bed", description: "Post-bed heavy-duty lockstitch for boot shafts, shoe uppers, and bags. The tall post arm and compound feed handle the demanding curved seams of footwear and leather goods.", max_speed_spm: 2000, stitch_length_max: 9.0, needle_system: "DPx17 (794)", needle_size_range: "#19–#24 (Nm 120–160)", bobbin_type: "DA large hook", presser_foot_height: 16.0, lift_height_max: 20.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1998 },
    { brand_id: bid["durkopp-adler"], model_name: "Dürkopp Adler 888", slug: "durkopp-adler-888", category: "walking-foot", description: "Extra-heavy-duty compound-feed machine for harnesses, safety equipment, horse tack, and military webbing. Handles thick layers with very large thread (Nm 15–35).", max_speed_spm: 1200, stitch_length_max: 15.0, needle_system: "DPx17 (794)", needle_size_range: "#22–#30 (Nm 140–200)", bobbin_type: "DA extra-large hook", presser_foot_height: 25.0, lift_height_max: 30.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1990 },
    { brand_id: bid["durkopp-adler"], model_name: "Dürkopp Adler 867", slug: "durkopp-adler-867", category: "cylinder-arm", description: "Cylinder-arm post-bed machine for shoes, bags, and saddles. The combination of the cylinder arm and compound feed allows precision stitching on three-dimensional leather goods.", max_speed_spm: 1800, stitch_length_max: 10.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "DA large hook", presser_foot_height: 14.0, lift_height_max: 16.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2002 },
  ];

  const allMachines = [...moreJuki, ...moreConsew, ...moreBrother, ...yamato, ...pegasus, ...jack, ...pfaff, ...durkopp];
  console.log(`Inserting ${allMachines.length} new machines…`);

  const { error: mErr } = await db.from("machines").upsert(allMachines, { onConflict: "slug" });
  if (mErr) { console.error("machines:", mErr); process.exit(1); }
  console.log(`Done. Inserted ${allMachines.length} machines across 5 new + 3 existing brands.`);

  // ── MORE TROUBLESHOOTING ─────────────────────────────────────────────────────
  const moreTroubleshooting = [
    { machine_id: null, symptom: "Overlock machine producing loose loops on the underside", slug: "overlock-loose-loops-underside", category: "tension", causes: ["Lower looper tension is too loose", "Thread is not correctly threaded through the lower looper guide", "Lower looper has a burr or damage on the thread path"], fixes: ["Remove and rethread the lower looper completely, following the colour-coded guide", "Increase the lower looper tension dial by 1–2 numbers and sew a test seam", "Inspect the lower looper for damage or rough spots — run a strand of thread over the surface to feel for burrs"], difficulty: "medium" },
    { machine_id: null, symptom: "Coverstitch looping on the underside (cover thread not catching)", slug: "coverstitch-looping-underside", category: "tension", causes: ["Looper thread tension is incorrect", "Machine was not threaded with the presser foot raised", "Looper thread path is incorrect"], fixes: ["Raise the presser foot and rethread the entire looper thread path", "Adjust the looper tension to balance it with the needle threads — start with all tensions equal", "Check that the looper thread goes through every guide in sequence before entering the looper eye"], difficulty: "medium" },
    { machine_id: null, symptom: "Walking foot not moving — fabric only feeding from the feed dogs", slug: "walking-foot-not-moving", category: "feed", causes: ["Walking foot is installed incorrectly — the fork that connects to the needle bar is missing or misplaced", "Walking foot presser bar height is set too low", "Internal mechanism of the walking foot is worn or broken"], fixes: ["Remove and reinstall the walking foot, ensuring the fork arm wraps around the needle bar clamp screw", "Raise the presser bar so the walking foot sole presses firmly against the fabric", "Test by lowering the foot and manually cycling the handwheel — the walking foot sole should move up and down with each stitch", "If the walking foot does not move at all, it may need replacement"], difficulty: "medium" },
    { machine_id: null, symptom: "Sewing machine runs but no stitch forms — thread not looping", slug: "no-stitch-forming", category: "timing", causes: ["Thread not through the needle eye", "Needle is installed backwards (flat side facing forward)", "Hook timing is severely off — hook is not catching the needle thread loop at any point"], fixes: ["Check the needle: remove it, reinsert with the flat side to the back, and push it fully into the clamp", "Rethread from the spool, ensuring thread passes through every guide and through the needle eye from front to back", "Slowly turn the handwheel one full rotation and watch whether the hook tip passes close to the needle — if it misses by more than 3mm, timing has shifted and needs professional adjustment"], difficulty: "hard" },
    { machine_id: null, symptom: "Thread tension varies stitch to stitch — inconsistent stitch quality", slug: "inconsistent-thread-tension", category: "tension", causes: ["Thread twist direction doesn't match the machine (Z-twist vs S-twist)", "Thread is catching on the spool or thread stand", "Tension disc has debris or thread fragments wedged inside it", "Spring on tension disc assembly is worn or missing"], fixes: ["Clean the tension discs: raise the presser foot, cut a strip of clean cloth slightly narrower than the disc gap, and pull it through while the foot is raised to remove debris", "Check the thread path from spool to needle for any snags, kinks, or rough guides", "Ensure the thread is wound off the spool in the correct direction for the machine", "If cleaning doesn't help, the tension spring may need replacing — a common wear item after years of use"], difficulty: "medium" },
    { machine_id: null, symptom: "Machine oil leaking onto fabric", slug: "machine-oil-leaking-fabric", category: "noise", causes: ["Machine has been over-oiled — excess oil is draining through the arm and dripping on fabric", "Machine was stored horizontally — oil has moved into areas it shouldn't reach", "Oil reservoir seal is damaged"], fixes: ["Wipe all accessible surfaces with a clean cloth to remove excess oil", "Run the machine for 5–10 minutes on scrap fabric — this flushes excess oil through without staining good fabric", "Only add oil when the sight glass shows oil below the minimum mark — more is not better", "If oil continues to drip excessively, have a technician inspect the reservoir seal"], difficulty: "easy" },
    { machine_id: null, symptom: "Presser foot leaving marks on fabric", slug: "presser-foot-marks-on-fabric", category: "feed", causes: ["Presser foot pressure is too high for the fabric weight", "Presser foot sole is scratched or has a rough edge", "Walking foot sole has worn grooves that grip and drag delicate fabric"], fixes: ["Reduce presser foot pressure — light fabrics need very low pressure", "Inspect the presser foot sole under good light and feel for rough edges — a worn foot should be replaced", "For delicate or napped fabrics (velvet, silk, suede), use a Teflon-coated foot or apply a strip of Teflon tape to the foot sole", "Adjust stitch length — shorter stitches reduce the distance each feed dog tooth travels, reducing drag marks"], difficulty: "easy" },
    { machine_id: null, symptom: "Buttonhole or bar tack stitching is asymmetric or misaligned", slug: "buttonhole-asymmetric", category: "other", causes: ["Fabric is not clamped flat or is shifting during the cycle", "Stitch count programming is off on computerised machines", "Mechanical linkage on the buttonhole cam is worn"], fixes: ["Ensure the fabric clamp on the buttonhole foot grips the fabric firmly before starting the cycle", "For computerised machines: reset the buttonhole program to factory defaults and reprogram", "Check that the presser foot and needle are aligned to the fabric grain before starting", "On mechanical buttonhole machines, have the cam linkage inspected if the machine is producing noticeably different left and right columns"], difficulty: "medium" },
  ];

  const { error: tsErr } = await db.from("troubleshooting").insert(moreTroubleshooting);
  if (tsErr) { console.error("troubleshooting:", tsErr); process.exit(1); }
  console.log(`Inserted ${moreTroubleshooting.length} more troubleshooting records.`);

  const { count } = await db.from("machines").select("*", { count: "exact", head: true });
  console.log(`\nTotal machines in DB: ${count}`);
}

run().catch((e) => { console.error(e); process.exit(1); });
