import { readFileSync } from "fs";
import { resolve } from "path";
// Load .env.local manually
try {
  const envFile = readFileSync(resolve(process.cwd(), ".env.local"), "utf8");
  for (const line of envFile.split("\n")) {
    const m = line.match(/^([^#=]+)=(.*)$/);
    if (m) process.env[m[1].trim()] = m[2].trim();
  }
} catch { /* ignore */ }
import { createClient } from "@supabase/supabase-js";

const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const db = createClient(url, key, { auth: { persistSession: false } });

async function run() {
  console.log("Seeding brands…");
  const { data: brands, error: brandErr } = await db.from("brands").upsert([
    { name: "Juki", slug: "juki", description: "The world's leading manufacturer of industrial sewing machines, used in factories across 170 countries. Founded 1938, Japan.", country: "Japan", website_url: "https://www.juki.com" },
    { name: "Consew", slug: "consew", description: "American industrial sewing machine brand known for walking-foot and compound-feed machines popular with upholsterers and leatherworkers.", country: "USA", website_url: "https://www.consew.com" },
    { name: "Brother Industrial", slug: "brother", description: "Industrial sewing division of Brother Industries. Reliable lockstitch and overlock machines widely used in Asian garment factories.", country: "Japan", website_url: "https://www.brother.com" },
    { name: "Singer Industrial", slug: "singer", description: "The original industrial sewing brand. Many vintage Singer models remain in active use decades after production ended.", country: "USA", website_url: "https://www.singer.com" },
    { name: "Chandler Machine", slug: "chandler", description: "US-based distributor and manufacturer known for cylinder-arm, post-bed, and walking-foot machines popular with leather and shoe craftspeople.", country: "USA", website_url: "https://www.chandlerequipment.com" },
  ], { onConflict: "slug" }).select("id,slug");
  if (brandErr) { console.error("brands:", brandErr); process.exit(1); }
  const bid = Object.fromEntries((brands ?? []).map((b: { id: string; slug: string }) => [b.slug, b.id]));
  console.log("Brands inserted:", Object.keys(bid));

  console.log("Seeding machines…");
  const machines = [
    // JUKI
    { brand_id: bid.juki, model_name: "Juki DDL-8700", slug: "juki-ddl-8700", category: "lockstitch", description: "The world's most popular single-needle lockstitch machine. Used in garment factories worldwide for light to medium fabrics. Reliable, fast, and easy to maintain.", max_speed_spm: 5500, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Juki large hook (class)", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: "https://www.goldstartool.com/files/Juki-DDL8700-instructions.pdf", manual_source: "retailer", discontinued: false, year_introduced: 1995 },
    { brand_id: bid.juki, model_name: "Juki DDL-8700-7", slug: "juki-ddl-8700-7", category: "lockstitch", description: "Automatic thread-trimming version of the DDL-8700. Trims both top and bobbin thread at the end of each seam with a foot pedal tap.", max_speed_spm: 5000, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Juki large hook (class)", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: "https://www.manualslib.com/brand/juki/sewing-machine.html", manual_source: "manualslib", discontinued: false, year_introduced: 2000 },
    { brand_id: bid.juki, model_name: "Juki DDL-9000C", slug: "juki-ddl-9000c", category: "lockstitch", description: "Computerised lockstitch machine with automatic thread trimming, backtacking, and presser foot lifter. Successor to the DDL-8700 series.", max_speed_spm: 5500, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Juki large hook (class)", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: "https://www.juki.com/sewing/en/products/industrial/lockstitch/", manual_source: "manufacturer", discontinued: false, year_introduced: 2012 },
    { brand_id: bid.juki, model_name: "Juki DDL-5550N", slug: "juki-ddl-5550n", category: "lockstitch", description: "Budget-friendly single-needle lockstitch machine. Fewer automatic features than the DDL-8700 but solid and reliable for light to medium work.", max_speed_spm: 5000, stitch_length_max: 4.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#16 (Nm 65–100)", bobbin_type: "Juki large hook (class)", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2005 },
    { brand_id: bid.juki, model_name: "Juki MO-6714S", slug: "juki-mo-6714s", category: "overlock", description: "4-thread overlock/serger machine. Widely used in garment factories for seam finishing. Differential feed prevents stretching or puckering on knits.", max_speed_spm: 7000, stitch_length_max: 4.0, needle_system: "DCx27 (ELx705)", needle_size_range: "#9–#14 (Nm 65–90)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: "https://www.juki.com/sewing/en/products/industrial/overlock/", manual_source: "manufacturer", discontinued: false, year_introduced: 2008 },
    { brand_id: bid.juki, model_name: "Juki MO-3916GN", slug: "juki-mo-3916gn", category: "overlock", description: "3–4 thread overlock machine with built-in light. Suitable for light to medium knit and woven fabrics.", max_speed_spm: 6500, stitch_length_max: 4.0, needle_system: "DCx27 (ELx705)", needle_size_range: "#9–#14 (Nm 65–90)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2010 },
    { brand_id: bid.juki, model_name: "Juki LU-2210N-7", slug: "juki-lu-2210n-7", category: "walking-foot", description: "Unison-feed (needle feed + walking foot) lockstitch machine. Ideal for thick, quilted, or slippery materials like leather, canvas, and denim.", max_speed_spm: 2500, stitch_length_max: 9.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Juki large hook (class)", presser_foot_height: 13.0, lift_height_max: 16.0, manual_url: "https://www.juki.com/sewing/en/products/industrial/unison-feed/", manual_source: "manufacturer", discontinued: false, year_introduced: 2006 },
    { brand_id: bid.juki, model_name: "Juki DNU-1541", slug: "juki-dnu-1541", category: "walking-foot", description: "Heavy-duty unison-feed machine for very thick materials: multiple layers of leather, canvas, webbing, and automotive upholstery.", max_speed_spm: 1500, stitch_length_max: 9.0, needle_system: "DPx17 (794)", needle_size_range: "#19–#24 (Nm 120–160)", bobbin_type: "Juki large hook (class)", presser_foot_height: 16.0, lift_height_max: 20.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2002 },
    { brand_id: bid.juki, model_name: "Juki MF-7923-U11-B56", slug: "juki-mf-7923", category: "coverstitch", description: "3-needle coverstitch machine. Creates the stretchy, professional hem seen on t-shirts, activewear, and swimwear.", max_speed_spm: 6000, stitch_length_max: 4.0, needle_system: "UYx128GAS", needle_size_range: "#11–#16 (Nm 75–100)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2010 },
    // CONSEW
    { brand_id: bid.consew, model_name: "Consew 206RB-5", slug: "consew-206rb-5", category: "walking-foot", description: "The most popular walking-foot machine in the US. Compound needle and walking foot feed handles leather, canvas, upholstery, and multiple layers with ease.", max_speed_spm: 2500, stitch_length_max: 10.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Consew large hook", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: "https://www.supsew.com/download/Consew/Consew%20206RB-5%20Operating%20Instructions.pdf", manual_source: "retailer", discontinued: false, year_introduced: 1985 },
    { brand_id: bid.consew, model_name: "Consew 226R-2", slug: "consew-226r-2", category: "walking-foot", description: "Compact walking-foot machine suitable for lighter upholstery, leather, and canvas work. Smaller format than the 206RB-5.", max_speed_spm: 2500, stitch_length_max: 9.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#21 (Nm 100–130)", bobbin_type: "Consew large hook", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1990 },
    { brand_id: bid.consew, model_name: "Consew 290", slug: "consew-290", category: "blind-stitch", description: "Industrial blind-stitch hemming machine. Creates an invisible hem on trousers, skirts, and curtains without the stitch showing on the right side.", max_speed_spm: 2800, stitch_length_max: 3.0, needle_system: "TVx7", needle_size_range: "#11–#16 (Nm 75–100)", bobbin_type: null, presser_foot_height: null, lift_height_max: null, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1980 },
    { brand_id: bid.consew, model_name: "Consew 339RB", slug: "consew-339rb", category: "walking-foot", description: "Three-feed compound walking-foot machine with roller presser foot option. Designed for very thick, slippery, or structured materials.", max_speed_spm: 2000, stitch_length_max: 10.0, needle_system: "DPx5 (135x17)", needle_size_range: "#18–#24 (Nm 110–160)", bobbin_type: "Consew large hook", presser_foot_height: 16.0, lift_height_max: 18.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1995 },
    { brand_id: bid.consew, model_name: "Consew 287RB-2", slug: "consew-287rb-2", category: "walking-foot", description: "Walking foot machine with roller presser foot. The roller eliminates drag on sticky or textured materials like PVC, rubber-backed fabric, and vinyl.", max_speed_spm: 2500, stitch_length_max: 10.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Consew large hook", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1992 },
    { brand_id: bid.consew, model_name: "Consew 255RB", slug: "consew-255rb", category: "walking-foot", description: "Post-bed walking-foot machine. The cylindrical bed allows stitching on boots, gloves, and curved seams that a flat-bed machine cannot reach.", max_speed_spm: 2000, stitch_length_max: 9.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Consew large hook", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1988 },
    // BROTHER
    { brand_id: bid.brother, model_name: "Brother DB2-B791", slug: "brother-db2-b791", category: "lockstitch", description: "One of the most widely used industrial lockstitch machines in Asia. Reliable, low-maintenance, and compatible with standard DBx1 needles and accessories.", max_speed_spm: 5000, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Brother large hook", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: "https://www.manualslib.com/brand/brother/sewing-machine.html", manual_source: "manualslib", discontinued: false, year_introduced: 1995 },
    { brand_id: bid.brother, model_name: "Brother DB2-B737", slug: "brother-db2-b737", category: "lockstitch", description: "Standard industrial lockstitch machine. Interchangeable parts with the DB2-B791 series. Popular in Bangladesh, Vietnam, and Pakistan garment industries.", max_speed_spm: 5000, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Brother large hook", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 1990 },
    { brand_id: bid.brother, model_name: "Brother B7100A", slug: "brother-b7100a", category: "lockstitch", description: "Needle-feed lockstitch machine. The needle moves with the fabric feed, preventing slippage on slippery fabrics like silk or microfiber.", max_speed_spm: 4500, stitch_length_max: 5.0, needle_system: "DBx1 (16x231, 135x17)", needle_size_range: "#9–#16 (Nm 65–100)", bobbin_type: "Brother large hook", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2005 },
    { brand_id: bid.brother, model_name: "Brother MA4-B551", slug: "brother-ma4-b551", category: "overlock", description: "4-thread overlock machine. Compact and fast with easy threading. Used for light to medium seam finishing in garment factories.", max_speed_spm: 7000, stitch_length_max: 4.0, needle_system: "DCx27 (ELx705)", needle_size_range: "#9–#14 (Nm 65–90)", bobbin_type: null, presser_foot_height: 6.0, lift_height_max: 6.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2008 },
    { brand_id: bid.brother, model_name: "Brother LT2-B842", slug: "brother-lt2-b842", category: "lockstitch", description: "Heavy-duty lockstitch machine for denim, canvas, and multiple layers. Larger hook capacity than standard industrial machines.", max_speed_spm: 3500, stitch_length_max: 6.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Brother large hook", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2003 },
    // SINGER
    { brand_id: bid.singer, model_name: "Singer 111W155", slug: "singer-111w155", category: "walking-foot", description: "A legendary vintage walking-foot machine, highly sought after by leatherworkers, upholsterers, and sailmakers. Extremely robust construction with a massive hook for heavy thread.", max_speed_spm: 3500, stitch_length_max: 9.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Singer long bobbin (class 66)", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: "https://www.manualslib.com/search/?q=Singer+111W155", manual_source: "manualslib", discontinued: true, year_introduced: 1955 },
    { brand_id: bid.singer, model_name: "Singer 211U", slug: "singer-211u", category: "lockstitch", description: "Large-hook lockstitch machine designed for heavy thread. The 211U series was used in denim, canvas, and upholstery applications. Many variants (211U13, 211U14, etc.) exist.", max_speed_spm: 4000, stitch_length_max: 6.0, needle_system: "DBx1 (16x231)", needle_size_range: "#14–#21 (Nm 90–130)", bobbin_type: "Singer large hook", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: "https://www.manualslib.com/search/?q=Singer+211U", manual_source: "manualslib", discontinued: true, year_introduced: 1965 },
    { brand_id: bid.singer, model_name: "Singer 31-15", slug: "singer-31-15", category: "lockstitch", description: "Classic vintage industrial lockstitch machine. Widely used in clothing factories in the mid-20th century. Parts and manuals are still widely available.", max_speed_spm: 3500, stitch_length_max: 5.0, needle_system: "DBx1 (16x231)", needle_size_range: "#9–#18 (Nm 65–110)", bobbin_type: "Singer class 15", presser_foot_height: 13.0, lift_height_max: 13.0, manual_url: "https://www.manualslib.com/search/?q=Singer+31-15", manual_source: "manualslib", discontinued: true, year_introduced: 1930 },
    { brand_id: bid.singer, model_name: "Singer 591D300A", slug: "singer-591d300a", category: "lockstitch", description: "Heavy-duty single-needle lockstitch machine for denim, canvas, and leather. Designed for high-volume industrial use with an extended arm.", max_speed_spm: 3500, stitch_length_max: 6.0, needle_system: "DBx1 (16x231)", needle_size_range: "#14–#21 (Nm 90–130)", bobbin_type: "Singer large hook", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: null, manual_source: null, discontinued: true, year_introduced: 1975 },
    { brand_id: bid.singer, model_name: "Singer 132K6", slug: "singer-132k6", category: "cylinder-arm", description: "Cylinder-arm lockstitch machine for stitching shoes, boots, gloves, and curved seams. The narrow cylindrical bed reaches areas a flat-bed machine cannot.", max_speed_spm: 2500, stitch_length_max: 5.0, needle_system: "DBx1 (16x231)", needle_size_range: "#11–#18 (Nm 75–110)", bobbin_type: "Singer large hook", presser_foot_height: 12.0, lift_height_max: 12.0, manual_url: "https://www.manualslib.com/search/?q=Singer+132K6", manual_source: "manualslib", discontinued: true, year_introduced: 1950 },
    // CHANDLER
    { brand_id: bid.chandler, model_name: "Chandler 206RBT", slug: "chandler-206rbt", category: "walking-foot", description: "Chandler's compound-feed walking-foot machine, comparable to the Consew 206RB-5. Widely used by upholsterers, leatherworkers, and canvas workers.", max_speed_spm: 2500, stitch_length_max: 10.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Large hook", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2000 },
    { brand_id: bid.chandler, model_name: "Chandler 441-clone", slug: "chandler-441-clone", category: "walking-foot", description: "Chandler's version of the Cobra Class 4 / Techsew 2750 style compound-feed machine. Handles very heavy leather, webbing, and safety harness material.", max_speed_spm: 1500, stitch_length_max: 12.0, needle_system: "DPx17 (794)", needle_size_range: "#19–#26 (Nm 120–180)", bobbin_type: "Large hook (extra)", presser_foot_height: 20.0, lift_height_max: 25.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2010 },
    { brand_id: bid.chandler, model_name: "Chandler Cylinder Arm", slug: "chandler-cylinder-arm", category: "cylinder-arm", description: "Cylinder-bed walking-foot machine for boots, bags, and gloves. The narrow arm reaches curved seams that flat-bed machines cannot access.", max_speed_spm: 2000, stitch_length_max: 9.0, needle_system: "DPx5 (135x17)", needle_size_range: "#16–#22 (Nm 100–140)", bobbin_type: "Large hook", presser_foot_height: 14.0, lift_height_max: 14.0, manual_url: null, manual_source: null, discontinued: false, year_introduced: 2005 },
  ];

  const { error: machErr } = await db.from("machines").upsert(machines, { onConflict: "slug" });
  if (machErr) { console.error("machines:", machErr); process.exit(1); }
  console.log(`Inserted ${machines.length} machines`);

  console.log("Seeding troubleshooting…");
  const troubleshooting = [
    { machine_id: null, symptom: "Top thread tension too loose — loops appear on the underside", slug: "top-thread-loops-underside", category: "tension", causes: ["Upper tension discs are not engaging (presser foot was down when threading)", "Thread not seated correctly in the tension discs", "Thread take-up spring is worn or missing", "Bobbin thread tension too tight relative to top thread"], fixes: ["Raise the presser foot before re-threading — the foot must be up for the tension discs to open", "Re-thread completely from the spool, ensuring thread passes between both tension discs", "Check the thread take-up spring — replace if bent or missing", "Slightly loosen the bobbin case tension screw (turn counter-clockwise 1/4 turn at a time)"], difficulty: "easy" },
    { machine_id: null, symptom: "Top thread breaking repeatedly", slug: "top-thread-breaking", category: "tension", causes: ["Needle is bent, blunt, or wrong size for the thread", "Thread tension is too tight", "Thread is caught or fraying on the spool or path", "Thread is passing through a burr or rough spot on the machine", "Needle is not fully inserted — flat side not facing back"], fixes: ["Replace the needle — a bent needle is the most common cause and costs less than $1", "Check that needle is fully inserted with the flat side facing toward the back of the machine", "Reduce upper tension by 1–2 numbers and test on scrap", "Run your finger along the thread path from spool to needle — feel for any sharp edges or rough spots", "Check the thread spool is unwinding freely and isn't tangled"], difficulty: "easy" },
    { machine_id: null, symptom: "Bobbin thread breaking", slug: "bobbin-thread-breaking", category: "tension", causes: ["Bobbin case tension screw is too tight", "Bobbin is wound unevenly or the bobbin case is damaged", "Bobbin is inserted in the wrong direction", "Thread tail not pulled under the presser foot before starting"], fixes: ["Remove the bobbin case and reinsert the bobbin, ensuring thread feeds in the correct direction (usually clockwise when viewed from above)", "Check the bobbin for uneven winding — discard and rewind if the thread is lumpy or loose", "Loosen the bobbin case tension screw slightly (1/8 turn counter-clockwise)", "Always pull both thread tails under the presser foot before starting a seam"], difficulty: "easy" },
    { machine_id: null, symptom: "Thread bunching underneath the fabric (bird's nest)", slug: "thread-bunching-underneath", category: "tension", causes: ["Machine was not threaded with the presser foot raised", "Upper thread tension is too loose", "Thread is not caught in the take-up lever", "Starting a seam without holding thread tails"], fixes: ["Raise the presser foot and re-thread the entire top thread path from scratch", "Hold both thread tails (top and bobbin) behind the presser foot for the first 3–4 stitches", "Increase upper tension slightly", "Check that the thread passes through the take-up lever correctly"], difficulty: "easy" },
    { machine_id: null, symptom: "Uneven or inconsistent stitch length", slug: "uneven-stitch-length", category: "tension", causes: ["Fabric is being pulled or pushed through the machine instead of fed naturally", "Feed dog height is incorrect or feed dogs are worn", "Presser foot pressure is too low for the material", "Timing is slightly off"], fixes: ["Let the machine feed the fabric — don't push or pull", "Increase presser foot pressure for thick or heavy materials", "Check feed dog height — dogs should extend 0.8–1.0mm above the needle plate", "Clean lint from under the needle plate and around the feed dogs"], difficulty: "medium" },
    { machine_id: null, symptom: "Skipped stitches", slug: "skipped-stitches", category: "timing", causes: ["Needle is too fine for the thread being used", "Needle is blunt, bent, or installed incorrectly", "Hook timing is off — the hook tip is not catching the thread loop at the right moment", "Presser foot pressure too low — fabric lifting with the needle"], fixes: ["Replace the needle with a fresh one of the correct size for your thread", "Ensure the needle is pushed all the way up into the clamp before tightening", "Check hook timing: at the lowest needle position, the hook tip should be 2–3mm above the needle eye", "Increase presser foot pressure so the fabric stays flat during the feed stroke"], difficulty: "medium" },
    { machine_id: null, symptom: "Hook timing is off — needle hitting the hook or missing the loop", slug: "hook-timing-off", category: "timing", causes: ["Hook timing has shifted — common after a needle break or running the machine without thread", "Timing screws have loosened from vibration", "Hook or needle bar has been physically damaged"], fixes: ["Mark the current hook position with a marker before adjusting", "Bring the needle to its lowest point, then raise it 2–3mm. At this point the hook tip should be level with the needle eye and 0.1mm to the right of the needle", "Loosen the hook set screws and rotate the hook shaft to the correct position, then retighten", "Run slowly by hand through several stitches to verify timing before running at speed", "If unsure, take photos before adjusting and compare to your machine's service manual"], difficulty: "hard" },
    { machine_id: null, symptom: "Needle breaking repeatedly", slug: "needle-breaking", category: "timing", causes: ["Needle is hitting the hook — timing is off", "Needle is hitting the needle plate — plate is loose or needle is installed off-center", "Material is too thick for the needle size being used", "Operator is pulling the fabric sideways while the needle is down"], fixes: ["Stop immediately — a broken needle can damage the hook", "Check that the needle plate is seated flat and the screws are tight", "Verify needle is correctly installed and centered in the needle hole", "Use a larger needle for thick materials", "Never pull fabric sideways when the needle is in the down position"], difficulty: "medium" },
    { machine_id: null, symptom: "Machine not feeding fabric — fabric staying still", slug: "machine-not-feeding", category: "feed", causes: ["Feed dogs are lowered (drop-feed lever is engaged)", "Feed dog height is too low — dogs not clearing the needle plate", "Excessive lint buildup under the needle plate blocking feed dog movement", "Presser foot pressure is too high, clamping fabric to the plate"], fixes: ["Check that the drop-feed lever (usually on the side or back of the machine) is in the raised position", "Remove the needle plate and clean all lint and debris from the feed dog area", "Adjust the feed dog height using the eccentric screw — dogs should rise 0.8–1.0mm above the plate", "Reduce presser foot pressure and test"], difficulty: "easy" },
    { machine_id: null, symptom: "Fabric feeding unevenly — pucker or stretch on one side", slug: "fabric-feeding-unevenly", category: "feed", causes: ["Walking foot pads are worn unevenly (walking-foot machines)", "Differential feed ratio incorrect (overlock machines)", "Presser foot is not sitting flat on the fabric", "Feed dogs are worn on one side"], fixes: ["Inspect the presser foot — replace if the sole is worn or damaged", "On overlock machines, adjust the differential feed ratio to match the fabric type (higher for stretchy knits, lower for wovens)", "Check that the presser foot is attached securely and sitting flat", "Inspect feed dogs for wear — replace if teeth are worn smooth"], difficulty: "medium" },
    { machine_id: null, symptom: "Machine making loud knocking or clicking noise", slug: "loud-knocking-noise", category: "noise", causes: ["Machine is dry — oil level is critically low", "Hook race is dry or has debris in it", "Needle is bent and hitting the hook race", "Timing belt or V-belt is worn or cracked"], fixes: ["Oil all oiling points immediately following your machine's oil chart — a dry machine can seize within minutes", "Remove the hook and clean the hook race with a clean cloth — apply a small amount of machine oil", "Replace the needle and check for hook damage", "Inspect the drive belt — replace if cracked, glazed, or frayed"], difficulty: "medium" },
    { machine_id: null, symptom: "Machine running slower than normal or losing power", slug: "machine-running-slow", category: "noise", causes: ["Motor capacitor is failing (common on older machines)", "Drive belt is slipping or glazed", "Machine needs oiling — internal friction is high", "Clutch motor needs adjustment"], fixes: ["Oil all oiling points — a stiff machine draws more current and runs slower", "Check the drive belt tension — it should deflect about 1cm when pressed", "Clean the belt and pulley with a dry cloth to remove grease or oil that causes slipping", "Have the motor capacitor tested by an electrician — capacitor failure is common after 10–15 years"], difficulty: "medium" },
    { machine_id: null, symptom: "Needle thread not catching bobbin thread on first stitch", slug: "needle-not-catching-bobbin", category: "needle", causes: ["Thread take-up lever is not at its highest position when starting", "Bobbin thread tail is too short to be caught by the needle thread", "Thread tail is not pulled to the back under the presser foot"], fixes: ["Bring the needle to its highest position (turn handwheel toward you until take-up lever is at top)", "Pull both thread tails 15–20cm out to the back-left of the machine before starting", "Lower the presser foot, then begin sewing slowly — the first stitch should pull up the bobbin thread"], difficulty: "easy" },
    { machine_id: null, symptom: "Bobbin running out too quickly or bobbin tension inconsistent", slug: "bobbin-tension-inconsistent", category: "needle", causes: ["Bobbin is not wound evenly — thread piles up in the middle or ends", "Bobbin case spring tension is inconsistent or the spring is damaged", "Wrong bobbin size or type for this machine"], fixes: ["Wind bobbins at a consistent medium speed — avoid winding too fast which causes uneven thread", "Check the bobbin type — using the wrong size bobbin will cause tension issues that no adjustment can fix", "Test bobbin tension: holding the thread, the bobbin case should drop slowly under its own weight. Too easy = loosen screw, too tight = tighten screw"], difficulty: "easy" },
  ];

  const { error: tsErr } = await db.from("troubleshooting").insert(troubleshooting);
  if (tsErr) { console.error("troubleshooting:", tsErr); process.exit(1); }
  console.log(`Inserted ${troubleshooting.length} troubleshooting records`);
  console.log("Done!");
}

run().catch((e) => { console.error(e); process.exit(1); });
